use std::sync::Arc;

use rmcp::{
    ErrorData as McpError, RoleServer, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    schemars,
    service::RequestContext,
    tool, tool_handler, tool_router,
};
use serde_json::json;

use crate::api_client::{ApiClient, ListEventTypesFilters};

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListEventTypesArgs {
    /// Filter by status (e.g. CURRENT, ARCHIVED).
    #[serde(default)]
    pub status: Option<String>,
    /// Filter by application code.
    #[serde(default)]
    pub application: Option<String>,
    /// Filter by client ID (admin-scoped tokens only).
    #[serde(default, rename = "clientId")]
    pub client_id: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GetByIdArgs {
    /// Resource ID.
    pub id: String,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GetSchemaArgs {
    /// Event type ID.
    pub id: String,
    /// Schema version (e.g. "1.0"). If omitted, returns the CURRENT version.
    #[serde(default)]
    pub version: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListSubscriptionsArgs {
    /// Filter by client ID (admin-scoped tokens only).
    #[serde(default, rename = "clientId")]
    pub client_id: Option<String>,
}

#[derive(Clone)]
pub struct FcMcpServer {
    api: Arc<ApiClient>,
    // Consumed by code generated by `#[tool_router]`; clippy can't see that
    // through the macro expansion.
    #[allow(dead_code)]
    tool_router: ToolRouter<FcMcpServer>,
}

#[tool_router]
impl FcMcpServer {
    pub fn new(api: Arc<ApiClient>) -> Self {
        Self {
            api,
            tool_router: Self::tool_router(),
        }
    }

    #[tool(
        description = "List event types registered in FlowCatalyst. Optionally filter by status, application, or client ID."
    )]
    async fn list_event_types(
        &self,
        Parameters(args): Parameters<ListEventTypesArgs>,
    ) -> Result<CallToolResult, McpError> {
        let filters = ListEventTypesFilters {
            status: args.status.as_deref(),
            application: args.application.as_deref(),
            client_id: args.client_id.as_deref(),
        };
        match self.api.list_event_types(&filters).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Get detailed information about a specific event type, including all schema versions."
    )]
    async fn get_event_type(
        &self,
        Parameters(args): Parameters<GetByIdArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.get_event_type(&args.id).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Get the raw JSON Schema for a specific event type version. Defaults to the CURRENT version."
    )]
    async fn get_schema(
        &self,
        Parameters(args): Parameters<GetSchemaArgs>,
    ) -> Result<CallToolResult, McpError> {
        let event_type = match self.api.get_event_type(&args.id).await {
            Ok(v) => v,
            Err(e) => return Ok(error_text(e)),
        };

        let versions = event_type
            .get("specVersions")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();

        let chosen = match args.version.as_deref() {
            Some(v) => versions.iter().find(|sv| {
                sv.get("version").and_then(|s| s.as_str()) == Some(v)
            }),
            None => versions
                .iter()
                .find(|sv| sv.get("status").and_then(|s| s.as_str()) == Some("CURRENT")),
        };

        let Some(spec) = chosen else {
            let msg = match args.version.as_deref() {
                Some(v) => format!("schema version {v} not found for event type {}", args.id),
                None => format!("no CURRENT schema version found for event type {}", args.id),
            };
            return Ok(CallToolResult::error(vec![Content::text(msg)]));
        };

        let schema = spec.get("schema").cloned().unwrap_or(serde_json::Value::Null);
        let text = serde_json::to_string_pretty(&schema)
            .unwrap_or_else(|_| schema.to_string());
        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    #[tool(description = "List webhook subscriptions configured in FlowCatalyst (scoped to the authenticated client unless an admin clientId is provided).")]
    async fn list_subscriptions(
        &self,
        Parameters(args): Parameters<ListSubscriptionsArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.list_subscriptions(args.client_id.as_deref()).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(description = "Get detailed information about a specific subscription.")]
    async fn get_subscription(
        &self,
        Parameters(args): Parameters<GetByIdArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.get_subscription(&args.id).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }
}

#[tool_handler]
impl ServerHandler for FcMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new("flowcatalyst", env!("CARGO_PKG_VERSION")))
        .with_instructions(
            "FlowCatalyst MCP server. Provides read-only access to event types, JSON \
             schemas, and webhook subscriptions. Use list_event_types/get_event_type \
             to explore the catalog, get_schema to read JSON Schemas, and \
             list_subscriptions/get_subscription for webhook configuration.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        let resources = vec![
            RawResource::new("flowcatalyst://event-types", "Event Types".to_string())
                .no_annotation(),
            RawResource::new("flowcatalyst://subscriptions", "Subscriptions".to_string())
                .no_annotation(),
        ];
        Ok(ListResourcesResult {
            resources,
            next_cursor: None,
            meta: None,
        })
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        let uri = request.uri.clone();
        let result = match uri.as_str() {
            "flowcatalyst://event-types" => {
                self.api.list_event_types(&ListEventTypesFilters::default()).await
            }
            "flowcatalyst://subscriptions" => self.api.list_subscriptions(None).await,
            other => {
                if let Some(id) = other.strip_prefix("flowcatalyst://event-types/") {
                    self.api.get_event_type(id).await
                } else if let Some(id) = other.strip_prefix("flowcatalyst://subscriptions/") {
                    self.api.get_subscription(id).await
                } else {
                    return Err(McpError::resource_not_found(
                        "resource_not_found",
                        Some(json!({ "uri": uri })),
                    ));
                }
            }
        };

        match result {
            Ok(v) => {
                let text = serde_json::to_string_pretty(&v).unwrap_or_else(|_| v.to_string());
                Ok(ReadResourceResult::new(vec![ResourceContents::text(text, uri)]))
            }
            Err(e) => Err(McpError::internal_error(
                e.to_string(),
                None,
            )),
        }
    }
}

fn json_text(value: serde_json::Value) -> CallToolResult {
    let text = serde_json::to_string_pretty(&value).unwrap_or_else(|_| value.to_string());
    CallToolResult::success(vec![Content::text(text)])
}

fn error_text(e: anyhow::Error) -> CallToolResult {
    CallToolResult::error(vec![Content::text(e.to_string())])
}
