// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application.sql

package dbq

import (
	"context"
	"time"
)

const applicationDelete = `-- name: ApplicationDelete :exec
DELETE FROM app_applications WHERE id = $1
`

func (q *Queries) ApplicationDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, applicationDelete, id)
	return err
}

const applicationFindByCode = `-- name: ApplicationFindByCode :one
SELECT id, type, code, name, description, icon_url, website, logo, logo_mime_type,
       default_base_url, service_account_id, active, created_at, updated_at
FROM app_applications
WHERE code = $1
`

func (q *Queries) ApplicationFindByCode(ctx context.Context, code string) (AppApplication, error) {
	row := q.db.QueryRow(ctx, applicationFindByCode, code)
	var i AppApplication
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.Website,
		&i.Logo,
		&i.LogoMimeType,
		&i.DefaultBaseUrl,
		&i.ServiceAccountID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applicationFindByID = `-- name: ApplicationFindByID :one

SELECT id, type, code, name, description, icon_url, website, logo, logo_mime_type,
       default_base_url, service_account_id, active, created_at, updated_at
FROM app_applications
WHERE id = $1
`

// Queries for app_applications.
func (q *Queries) ApplicationFindByID(ctx context.Context, id string) (AppApplication, error) {
	row := q.db.QueryRow(ctx, applicationFindByID, id)
	var i AppApplication
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.Website,
		&i.Logo,
		&i.LogoMimeType,
		&i.DefaultBaseUrl,
		&i.ServiceAccountID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applicationUpsert = `-- name: ApplicationUpsert :exec
INSERT INTO app_applications
    (id, type, code, name, description, icon_url, website, logo, logo_mime_type,
     default_base_url, service_account_id, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    icon_url = EXCLUDED.icon_url,
    website = EXCLUDED.website,
    logo = EXCLUDED.logo,
    logo_mime_type = EXCLUDED.logo_mime_type,
    default_base_url = EXCLUDED.default_base_url,
    service_account_id = EXCLUDED.service_account_id,
    active = EXCLUDED.active,
    updated_at = EXCLUDED.updated_at
`

type ApplicationUpsertParams struct {
	ID               string
	Type             string
	Code             string
	Name             string
	Description      *string
	IconUrl          *string
	Website          *string
	Logo             *string
	LogoMimeType     *string
	DefaultBaseUrl   *string
	ServiceAccountID *string
	Active           bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ApplicationUpsert(ctx context.Context, arg ApplicationUpsertParams) error {
	_, err := q.db.Exec(ctx, applicationUpsert,
		arg.ID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.Website,
		arg.Logo,
		arg.LogoMimeType,
		arg.DefaultBaseUrl,
		arg.ServiceAccountID,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const clientConfigDelete = `-- name: ClientConfigDelete :exec
DELETE FROM app_client_configs WHERE id = $1
`

func (q *Queries) ClientConfigDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clientConfigDelete, id)
	return err
}

const clientConfigFindByApp = `-- name: ClientConfigFindByApp :many
SELECT id, application_id, client_id, enabled, created_at, updated_at
FROM app_client_configs
WHERE application_id = $1
ORDER BY created_at
`

func (q *Queries) ClientConfigFindByApp(ctx context.Context, applicationID string) ([]AppClientConfig, error) {
	rows, err := q.db.Query(ctx, clientConfigFindByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppClientConfig{}
	for rows.Next() {
		var i AppClientConfig
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ClientID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientConfigFindByAppAndClient = `-- name: ClientConfigFindByAppAndClient :one
SELECT id, application_id, client_id, enabled, created_at, updated_at
FROM app_client_configs
WHERE application_id = $1 AND client_id = $2
`

type ClientConfigFindByAppAndClientParams struct {
	ApplicationID string
	ClientID      string
}

func (q *Queries) ClientConfigFindByAppAndClient(ctx context.Context, arg ClientConfigFindByAppAndClientParams) (AppClientConfig, error) {
	row := q.db.QueryRow(ctx, clientConfigFindByAppAndClient, arg.ApplicationID, arg.ClientID)
	var i AppClientConfig
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ClientID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clientConfigUpsert = `-- name: ClientConfigUpsert :exec
INSERT INTO app_client_configs
    (id, application_id, client_id, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    updated_at = EXCLUDED.updated_at
`

type ClientConfigUpsertParams struct {
	ID            string
	ApplicationID string
	ClientID      string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ClientConfigUpsert(ctx context.Context, arg ClientConfigUpsertParams) error {
	_, err := q.db.Exec(ctx, clientConfigUpsert,
		arg.ID,
		arg.ApplicationID,
		arg.ClientID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
