// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const auditFindByID = `-- name: AuditFindByID :one

SELECT a.id, a.entity_type, a.entity_id, a.operation, a.operation_json,
       a.principal_id, p.name AS principal_name,
       a.application_id, a.client_id, a.performed_at
FROM aud_logs a
LEFT JOIN iam_principals p ON p.id = a.principal_id
WHERE a.id = $1
`

type AuditFindByIDRow struct {
	ID            string
	EntityType    string
	EntityID      string
	Operation     string
	OperationJson json.RawMessage
	PrincipalID   *string
	PrincipalName *string
	ApplicationID *string
	ClientID      *string
	PerformedAt   time.Time
}

// Queries for aud_logs (read-only — writes happen in platformsink).
func (q *Queries) AuditFindByID(ctx context.Context, id string) (AuditFindByIDRow, error) {
	row := q.db.QueryRow(ctx, auditFindByID, id)
	var i AuditFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Operation,
		&i.OperationJson,
		&i.PrincipalID,
		&i.PrincipalName,
		&i.ApplicationID,
		&i.ClientID,
		&i.PerformedAt,
	)
	return i, err
}

const auditFindWithFilters = `-- name: AuditFindWithFilters :many
SELECT a.id, a.entity_type, a.entity_id, a.operation, a.operation_json,
       a.principal_id, p.name AS principal_name,
       a.application_id, a.client_id, a.performed_at
FROM aud_logs a
LEFT JOIN iam_principals p ON p.id = a.principal_id
WHERE ($1::text IS NULL OR a.entity_type = $1::text)
  AND ($2::text IS NULL OR a.entity_id = $2::text)
  AND ($3::text IS NULL OR a.principal_id = $3::text)
  AND ($4::text IS NULL OR a.client_id = $4::text)
  AND ($5::timestamptz IS NULL OR a.performed_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR a.performed_at <= $6::timestamptz)
ORDER BY a.performed_at DESC
LIMIT $8::int OFFSET $7::int
`

type AuditFindWithFiltersParams struct {
	EntityType  *string
	EntityID    *string
	PrincipalID *string
	ClientID    *string
	Since       *time.Time
	Until       *time.Time
	Off         int32
	Lim         int32
}

type AuditFindWithFiltersRow struct {
	ID            string
	EntityType    string
	EntityID      string
	Operation     string
	OperationJson json.RawMessage
	PrincipalID   *string
	PrincipalName *string
	ApplicationID *string
	ClientID      *string
	PerformedAt   time.Time
}

// All filters are optional via the IS-NULL-OR pattern. Limit + offset
// are always bound. Ordered by most recent first.
func (q *Queries) AuditFindWithFilters(ctx context.Context, arg AuditFindWithFiltersParams) ([]AuditFindWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, auditFindWithFilters,
		arg.EntityType,
		arg.EntityID,
		arg.PrincipalID,
		arg.ClientID,
		arg.Since,
		arg.Until,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditFindWithFiltersRow{}
	for rows.Next() {
		var i AuditFindWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Operation,
			&i.OperationJson,
			&i.PrincipalID,
			&i.PrincipalName,
			&i.ApplicationID,
			&i.ClientID,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
