// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const anchorDomainDelete = `-- name: AnchorDomainDelete :exec
DELETE FROM tnt_anchor_domains WHERE id = $1
`

func (q *Queries) AnchorDomainDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, anchorDomainDelete, id)
	return err
}

const anchorDomainFindAll = `-- name: AnchorDomainFindAll :many
SELECT id, domain, created_at, updated_at
FROM tnt_anchor_domains
ORDER BY domain
`

func (q *Queries) AnchorDomainFindAll(ctx context.Context) ([]TntAnchorDomain, error) {
	rows, err := q.db.Query(ctx, anchorDomainFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TntAnchorDomain{}
	for rows.Next() {
		var i TntAnchorDomain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anchorDomainFindByDomain = `-- name: AnchorDomainFindByDomain :one
SELECT id, domain, created_at, updated_at
FROM tnt_anchor_domains
WHERE domain = $1
`

func (q *Queries) AnchorDomainFindByDomain(ctx context.Context, domain string) (TntAnchorDomain, error) {
	row := q.db.QueryRow(ctx, anchorDomainFindByDomain, domain)
	var i TntAnchorDomain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const anchorDomainFindByID = `-- name: AnchorDomainFindByID :one

SELECT id, domain, created_at, updated_at
FROM tnt_anchor_domains
WHERE id = $1
`

// ── AnchorDomain (tnt_anchor_domains) ────────────────────────────────
func (q *Queries) AnchorDomainFindByID(ctx context.Context, id string) (TntAnchorDomain, error) {
	row := q.db.QueryRow(ctx, anchorDomainFindByID, id)
	var i TntAnchorDomain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const anchorDomainUpsert = `-- name: AnchorDomainUpsert :exec
INSERT INTO tnt_anchor_domains (id, domain, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    domain = EXCLUDED.domain,
    updated_at = EXCLUDED.updated_at
`

type AnchorDomainUpsertParams struct {
	ID        string
	Domain    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) AnchorDomainUpsert(ctx context.Context, arg AnchorDomainUpsertParams) error {
	_, err := q.db.Exec(ctx, anchorDomainUpsert,
		arg.ID,
		arg.Domain,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const clientAuthConfigDelete = `-- name: ClientAuthConfigDelete :exec
DELETE FROM tnt_client_auth_configs WHERE id = $1
`

func (q *Queries) ClientAuthConfigDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clientAuthConfigDelete, id)
	return err
}

const clientAuthConfigFindAll = `-- name: ClientAuthConfigFindAll :many
SELECT id, email_domain, config_type, primary_client_id,
       additional_client_ids, granted_client_ids,
       auth_provider, oidc_issuer_url, oidc_client_id, oidc_multi_tenant,
       oidc_issuer_pattern, oidc_client_secret_ref, created_at, updated_at
FROM tnt_client_auth_configs
ORDER BY email_domain
`

func (q *Queries) ClientAuthConfigFindAll(ctx context.Context) ([]TntClientAuthConfig, error) {
	rows, err := q.db.Query(ctx, clientAuthConfigFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TntClientAuthConfig{}
	for rows.Next() {
		var i TntClientAuthConfig
		if err := rows.Scan(
			&i.ID,
			&i.EmailDomain,
			&i.ConfigType,
			&i.PrimaryClientID,
			&i.AdditionalClientIds,
			&i.GrantedClientIds,
			&i.AuthProvider,
			&i.OidcIssuerUrl,
			&i.OidcClientID,
			&i.OidcMultiTenant,
			&i.OidcIssuerPattern,
			&i.OidcClientSecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientAuthConfigFindByEmailDomain = `-- name: ClientAuthConfigFindByEmailDomain :one
SELECT id, email_domain, config_type, primary_client_id,
       additional_client_ids, granted_client_ids,
       auth_provider, oidc_issuer_url, oidc_client_id, oidc_multi_tenant,
       oidc_issuer_pattern, oidc_client_secret_ref, created_at, updated_at
FROM tnt_client_auth_configs
WHERE email_domain = $1
`

func (q *Queries) ClientAuthConfigFindByEmailDomain(ctx context.Context, emailDomain string) (TntClientAuthConfig, error) {
	row := q.db.QueryRow(ctx, clientAuthConfigFindByEmailDomain, emailDomain)
	var i TntClientAuthConfig
	err := row.Scan(
		&i.ID,
		&i.EmailDomain,
		&i.ConfigType,
		&i.PrimaryClientID,
		&i.AdditionalClientIds,
		&i.GrantedClientIds,
		&i.AuthProvider,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcMultiTenant,
		&i.OidcIssuerPattern,
		&i.OidcClientSecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clientAuthConfigFindByID = `-- name: ClientAuthConfigFindByID :one

SELECT id, email_domain, config_type, primary_client_id,
       additional_client_ids, granted_client_ids,
       auth_provider, oidc_issuer_url, oidc_client_id, oidc_multi_tenant,
       oidc_issuer_pattern, oidc_client_secret_ref, created_at, updated_at
FROM tnt_client_auth_configs
WHERE id = $1
`

// ── ClientAuthConfig (tnt_client_auth_configs) ───────────────────────
func (q *Queries) ClientAuthConfigFindByID(ctx context.Context, id string) (TntClientAuthConfig, error) {
	row := q.db.QueryRow(ctx, clientAuthConfigFindByID, id)
	var i TntClientAuthConfig
	err := row.Scan(
		&i.ID,
		&i.EmailDomain,
		&i.ConfigType,
		&i.PrimaryClientID,
		&i.AdditionalClientIds,
		&i.GrantedClientIds,
		&i.AuthProvider,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcMultiTenant,
		&i.OidcIssuerPattern,
		&i.OidcClientSecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clientAuthConfigUpsert = `-- name: ClientAuthConfigUpsert :exec
INSERT INTO tnt_client_auth_configs
    (id, email_domain, config_type, primary_client_id,
     additional_client_ids, granted_client_ids,
     auth_provider, oidc_issuer_url, oidc_client_id, oidc_multi_tenant,
     oidc_issuer_pattern, oidc_client_secret_ref, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    email_domain = EXCLUDED.email_domain,
    config_type = EXCLUDED.config_type,
    primary_client_id = EXCLUDED.primary_client_id,
    additional_client_ids = EXCLUDED.additional_client_ids,
    granted_client_ids = EXCLUDED.granted_client_ids,
    auth_provider = EXCLUDED.auth_provider,
    oidc_issuer_url = EXCLUDED.oidc_issuer_url,
    oidc_client_id = EXCLUDED.oidc_client_id,
    oidc_multi_tenant = EXCLUDED.oidc_multi_tenant,
    oidc_issuer_pattern = EXCLUDED.oidc_issuer_pattern,
    oidc_client_secret_ref = EXCLUDED.oidc_client_secret_ref,
    updated_at = EXCLUDED.updated_at
`

type ClientAuthConfigUpsertParams struct {
	ID                  string
	EmailDomain         string
	ConfigType          string
	PrimaryClientID     *string
	AdditionalClientIds json.RawMessage
	GrantedClientIds    json.RawMessage
	AuthProvider        string
	OidcIssuerUrl       *string
	OidcClientID        *string
	OidcMultiTenant     bool
	OidcIssuerPattern   *string
	OidcClientSecretRef *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ClientAuthConfigUpsert(ctx context.Context, arg ClientAuthConfigUpsertParams) error {
	_, err := q.db.Exec(ctx, clientAuthConfigUpsert,
		arg.ID,
		arg.EmailDomain,
		arg.ConfigType,
		arg.PrimaryClientID,
		arg.AdditionalClientIds,
		arg.GrantedClientIds,
		arg.AuthProvider,
		arg.OidcIssuerUrl,
		arg.OidcClientID,
		arg.OidcMultiTenant,
		arg.OidcIssuerPattern,
		arg.OidcClientSecretRef,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const idpRoleMappingDelete = `-- name: IdpRoleMappingDelete :exec
DELETE FROM oauth_idp_role_mappings WHERE id = $1
`

func (q *Queries) IdpRoleMappingDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, idpRoleMappingDelete, id)
	return err
}

const idpRoleMappingFindAll = `-- name: IdpRoleMappingFindAll :many
SELECT id, idp_role_name, internal_role_name, created_at, updated_at
FROM oauth_idp_role_mappings
ORDER BY idp_role_name
`

func (q *Queries) IdpRoleMappingFindAll(ctx context.Context) ([]OauthIdpRoleMapping, error) {
	rows, err := q.db.Query(ctx, idpRoleMappingFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdpRoleMapping{}
	for rows.Next() {
		var i OauthIdpRoleMapping
		if err := rows.Scan(
			&i.ID,
			&i.IdpRoleName,
			&i.InternalRoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const idpRoleMappingFindByID = `-- name: IdpRoleMappingFindByID :one

SELECT id, idp_role_name, internal_role_name, created_at, updated_at
FROM oauth_idp_role_mappings
WHERE id = $1
`

// ── IdpRoleMapping (oauth_idp_role_mappings) ─────────────────────────
// Schema columns: id, idp_role_name, internal_role_name, created_at,
// updated_at. The Go entity carries an `IdpType` field that has no
// backing column today (matches Rust, where the column was dropped);
// the field is ignored on persist and reads back as "".
func (q *Queries) IdpRoleMappingFindByID(ctx context.Context, id string) (OauthIdpRoleMapping, error) {
	row := q.db.QueryRow(ctx, idpRoleMappingFindByID, id)
	var i OauthIdpRoleMapping
	err := row.Scan(
		&i.ID,
		&i.IdpRoleName,
		&i.InternalRoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const idpRoleMappingFindByIdpRole = `-- name: IdpRoleMappingFindByIdpRole :many
SELECT id, idp_role_name, internal_role_name, created_at, updated_at
FROM oauth_idp_role_mappings
WHERE idp_role_name = $1
ORDER BY internal_role_name
`

func (q *Queries) IdpRoleMappingFindByIdpRole(ctx context.Context, idpRoleName string) ([]OauthIdpRoleMapping, error) {
	rows, err := q.db.Query(ctx, idpRoleMappingFindByIdpRole, idpRoleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdpRoleMapping{}
	for rows.Next() {
		var i OauthIdpRoleMapping
		if err := rows.Scan(
			&i.ID,
			&i.IdpRoleName,
			&i.InternalRoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const idpRoleMappingUpsert = `-- name: IdpRoleMappingUpsert :exec
INSERT INTO oauth_idp_role_mappings
    (id, idp_role_name, internal_role_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    internal_role_name = EXCLUDED.internal_role_name,
    updated_at = EXCLUDED.updated_at
`

type IdpRoleMappingUpsertParams struct {
	ID               string
	IdpRoleName      string
	InternalRoleName string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) IdpRoleMappingUpsert(ctx context.Context, arg IdpRoleMappingUpsertParams) error {
	_, err := q.db.Exec(ctx, idpRoleMappingUpsert,
		arg.ID,
		arg.IdpRoleName,
		arg.InternalRoleName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const oAuthClientDelete = `-- name: OAuthClientDelete :exec
DELETE FROM oauth_clients WHERE id = $1
`

func (q *Queries) OAuthClientDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, oAuthClientDelete, id)
	return err
}

const oAuthClientFindAll = `-- name: OAuthClientFindAll :many
SELECT id, client_id, client_name, client_type, client_secret_ref,
       default_scopes, pkce_required, service_account_principal_id,
       active, created_at, updated_at
FROM oauth_clients
ORDER BY client_name
`

func (q *Queries) OAuthClientFindAll(ctx context.Context) ([]OauthClient, error) {
	rows, err := q.db.Query(ctx, oAuthClientFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClient{}
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.ClientType,
			&i.ClientSecretRef,
			&i.DefaultScopes,
			&i.PkceRequired,
			&i.ServiceAccountPrincipalID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oAuthClientFindByClientID = `-- name: OAuthClientFindByClientID :one
SELECT id, client_id, client_name, client_type, client_secret_ref,
       default_scopes, pkce_required, service_account_principal_id,
       active, created_at, updated_at
FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) OAuthClientFindByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, oAuthClientFindByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientType,
		&i.ClientSecretRef,
		&i.DefaultScopes,
		&i.PkceRequired,
		&i.ServiceAccountPrincipalID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const oAuthClientFindByID = `-- name: OAuthClientFindByID :one


SELECT id, client_id, client_name, client_type, client_secret_ref,
       default_scopes, pkce_required, service_account_principal_id,
       active, created_at, updated_at
FROM oauth_clients
WHERE id = $1
`

// Queries for the auth subdomain: OAuthClient + AnchorDomain +
// ClientAuthConfig + IdpRoleMapping aggregates.
// ── OAuthClient (oauth_clients + 2 junctions wired today) ────────────
// The schema also has 3 more junctions (post_logout_redirect_uris,
// allowed_origins, application_ids) that the Go entity doesn't carry
// yet — they're a follow-up alongside the entity extension.
// The Go entity stores Argon2-hashed secrets in client_secret_ref
// (Rust uses it as a secrets-manager reference; Go uses it as the
// hash). See HANDOFF.md §4 for the planned PHC-salt fix.
func (q *Queries) OAuthClientFindByID(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, oAuthClientFindByID, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientType,
		&i.ClientSecretRef,
		&i.DefaultScopes,
		&i.PkceRequired,
		&i.ServiceAccountPrincipalID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const oAuthClientGrantTypeInsert = `-- name: OAuthClientGrantTypeInsert :exec
INSERT INTO oauth_client_grant_types (oauth_client_id, grant_type)
VALUES ($1, $2)
`

type OAuthClientGrantTypeInsertParams struct {
	OauthClientID string
	GrantType     string
}

func (q *Queries) OAuthClientGrantTypeInsert(ctx context.Context, arg OAuthClientGrantTypeInsertParams) error {
	_, err := q.db.Exec(ctx, oAuthClientGrantTypeInsert, arg.OauthClientID, arg.GrantType)
	return err
}

const oAuthClientGrantTypesClear = `-- name: OAuthClientGrantTypesClear :exec
DELETE FROM oauth_client_grant_types WHERE oauth_client_id = $1
`

func (q *Queries) OAuthClientGrantTypesClear(ctx context.Context, oauthClientID string) error {
	_, err := q.db.Exec(ctx, oAuthClientGrantTypesClear, oauthClientID)
	return err
}

const oAuthClientGrantTypesForClient = `-- name: OAuthClientGrantTypesForClient :many
SELECT grant_type FROM oauth_client_grant_types
WHERE oauth_client_id = $1
`

func (q *Queries) OAuthClientGrantTypesForClient(ctx context.Context, oauthClientID string) ([]string, error) {
	rows, err := q.db.Query(ctx, oAuthClientGrantTypesForClient, oauthClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var grant_type string
		if err := rows.Scan(&grant_type); err != nil {
			return nil, err
		}
		items = append(items, grant_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oAuthClientGrantTypesForClients = `-- name: OAuthClientGrantTypesForClients :many
SELECT oauth_client_id, grant_type
FROM oauth_client_grant_types
WHERE oauth_client_id = ANY($1::varchar[])
`

func (q *Queries) OAuthClientGrantTypesForClients(ctx context.Context, dollar_1 []string) ([]OauthClientGrantType, error) {
	rows, err := q.db.Query(ctx, oAuthClientGrantTypesForClients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClientGrantType{}
	for rows.Next() {
		var i OauthClientGrantType
		if err := rows.Scan(&i.OauthClientID, &i.GrantType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oAuthClientRedirectURIInsert = `-- name: OAuthClientRedirectURIInsert :exec
INSERT INTO oauth_client_redirect_uris (oauth_client_id, redirect_uri)
VALUES ($1, $2)
`

type OAuthClientRedirectURIInsertParams struct {
	OauthClientID string
	RedirectUri   string
}

func (q *Queries) OAuthClientRedirectURIInsert(ctx context.Context, arg OAuthClientRedirectURIInsertParams) error {
	_, err := q.db.Exec(ctx, oAuthClientRedirectURIInsert, arg.OauthClientID, arg.RedirectUri)
	return err
}

const oAuthClientRedirectURIsClear = `-- name: OAuthClientRedirectURIsClear :exec
DELETE FROM oauth_client_redirect_uris WHERE oauth_client_id = $1
`

func (q *Queries) OAuthClientRedirectURIsClear(ctx context.Context, oauthClientID string) error {
	_, err := q.db.Exec(ctx, oAuthClientRedirectURIsClear, oauthClientID)
	return err
}

const oAuthClientRedirectURIsForClient = `-- name: OAuthClientRedirectURIsForClient :many
SELECT redirect_uri FROM oauth_client_redirect_uris
WHERE oauth_client_id = $1
`

func (q *Queries) OAuthClientRedirectURIsForClient(ctx context.Context, oauthClientID string) ([]string, error) {
	rows, err := q.db.Query(ctx, oAuthClientRedirectURIsForClient, oauthClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var redirect_uri string
		if err := rows.Scan(&redirect_uri); err != nil {
			return nil, err
		}
		items = append(items, redirect_uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oAuthClientRedirectURIsForClients = `-- name: OAuthClientRedirectURIsForClients :many
SELECT oauth_client_id, redirect_uri
FROM oauth_client_redirect_uris
WHERE oauth_client_id = ANY($1::varchar[])
`

func (q *Queries) OAuthClientRedirectURIsForClients(ctx context.Context, dollar_1 []string) ([]OauthClientRedirectUri, error) {
	rows, err := q.db.Query(ctx, oAuthClientRedirectURIsForClients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClientRedirectUri{}
	for rows.Next() {
		var i OauthClientRedirectUri
		if err := rows.Scan(&i.OauthClientID, &i.RedirectUri); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oAuthClientUpsert = `-- name: OAuthClientUpsert :exec
INSERT INTO oauth_clients
    (id, client_id, client_name, client_type, client_secret_ref,
     default_scopes, pkce_required, service_account_principal_id,
     active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    client_id = EXCLUDED.client_id,
    client_name = EXCLUDED.client_name,
    client_type = EXCLUDED.client_type,
    client_secret_ref = EXCLUDED.client_secret_ref,
    default_scopes = EXCLUDED.default_scopes,
    pkce_required = EXCLUDED.pkce_required,
    service_account_principal_id = EXCLUDED.service_account_principal_id,
    active = EXCLUDED.active,
    updated_at = EXCLUDED.updated_at
`

type OAuthClientUpsertParams struct {
	ID                        string
	ClientID                  string
	ClientName                string
	ClientType                string
	ClientSecretRef           *string
	DefaultScopes             *string
	PkceRequired              bool
	ServiceAccountPrincipalID *string
	Active                    bool
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

func (q *Queries) OAuthClientUpsert(ctx context.Context, arg OAuthClientUpsertParams) error {
	_, err := q.db.Exec(ctx, oAuthClientUpsert,
		arg.ID,
		arg.ClientID,
		arg.ClientName,
		arg.ClientType,
		arg.ClientSecretRef,
		arg.DefaultScopes,
		arg.PkceRequired,
		arg.ServiceAccountPrincipalID,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
