// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const clientDelete = `-- name: ClientDelete :exec
DELETE FROM tnt_clients WHERE id = $1
`

func (q *Queries) ClientDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clientDelete, id)
	return err
}

const clientFindAll = `-- name: ClientFindAll :many
SELECT id, name, identifier, status, status_reason, status_changed_at,
       notes, created_at, updated_at
FROM tnt_clients
ORDER BY identifier
`

func (q *Queries) ClientFindAll(ctx context.Context) ([]TntClient, error) {
	rows, err := q.db.Query(ctx, clientFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TntClient{}
	for rows.Next() {
		var i TntClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Identifier,
			&i.Status,
			&i.StatusReason,
			&i.StatusChangedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientFindByID = `-- name: ClientFindByID :one

SELECT id, name, identifier, status, status_reason, status_changed_at,
       notes, created_at, updated_at
FROM tnt_clients
WHERE id = $1
`

// All queries operating on tnt_clients. The Repository wrapper in
// internal/platform/client maps the generated row type onto the
// aggregate's Client struct.
func (q *Queries) ClientFindByID(ctx context.Context, id string) (TntClient, error) {
	row := q.db.QueryRow(ctx, clientFindByID, id)
	var i TntClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Identifier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clientFindByIdentifier = `-- name: ClientFindByIdentifier :one
SELECT id, name, identifier, status, status_reason, status_changed_at,
       notes, created_at, updated_at
FROM tnt_clients
WHERE identifier = $1
`

func (q *Queries) ClientFindByIdentifier(ctx context.Context, identifier string) (TntClient, error) {
	row := q.db.QueryRow(ctx, clientFindByIdentifier, identifier)
	var i TntClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Identifier,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clientSearch = `-- name: ClientSearch :many
SELECT id, name, identifier, status, status_reason, status_changed_at,
       notes, created_at, updated_at
FROM tnt_clients
WHERE name ILIKE $1 OR identifier ILIKE $1
ORDER BY identifier
LIMIT 50
`

func (q *Queries) ClientSearch(ctx context.Context, pattern string) ([]TntClient, error) {
	rows, err := q.db.Query(ctx, clientSearch, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TntClient{}
	for rows.Next() {
		var i TntClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Identifier,
			&i.Status,
			&i.StatusReason,
			&i.StatusChangedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientUpsert = `-- name: ClientUpsert :exec
INSERT INTO tnt_clients
    (id, name, identifier, status, status_reason, status_changed_at,
     notes, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    identifier = EXCLUDED.identifier,
    status = EXCLUDED.status,
    status_reason = EXCLUDED.status_reason,
    status_changed_at = EXCLUDED.status_changed_at,
    notes = EXCLUDED.notes,
    updated_at = EXCLUDED.updated_at
`

type ClientUpsertParams struct {
	ID              string          `db:"id"`
	Name            string          `db:"name"`
	Identifier      string          `db:"identifier"`
	Status          string          `db:"status"`
	StatusReason    *string         `db:"status_reason"`
	StatusChangedAt *time.Time      `db:"status_changed_at"`
	Notes           json.RawMessage `db:"notes"`
	CreatedAt       time.Time       `db:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at"`
}

func (q *Queries) ClientUpsert(ctx context.Context, arg ClientUpsertParams) error {
	_, err := q.db.Exec(ctx, clientUpsert,
		arg.ID,
		arg.Name,
		arg.Identifier,
		arg.Status,
		arg.StatusReason,
		arg.StatusChangedAt,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
