// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection.sql

package dbq

import (
	"context"
	"time"
)

const connectionDelete = `-- name: ConnectionDelete :exec
DELETE FROM msg_connections WHERE id = $1
`

func (q *Queries) ConnectionDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, connectionDelete, id)
	return err
}

const connectionFindAll = `-- name: ConnectionFindAll :many
SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at
FROM msg_connections
ORDER BY code
`

func (q *Queries) ConnectionFindAll(ctx context.Context) ([]MsgConnection, error) {
	rows, err := q.db.Query(ctx, connectionFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgConnection{}
	for rows.Next() {
		var i MsgConnection
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ServiceAccountID,
			&i.ClientID,
			&i.ClientIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionFindByCodeAnchor = `-- name: ConnectionFindByCodeAnchor :one
SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at
FROM msg_connections
WHERE code = $1 AND client_id IS NULL
`

func (q *Queries) ConnectionFindByCodeAnchor(ctx context.Context, code string) (MsgConnection, error) {
	row := q.db.QueryRow(ctx, connectionFindByCodeAnchor, code)
	var i MsgConnection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const connectionFindByCodeClient = `-- name: ConnectionFindByCodeClient :one
SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at
FROM msg_connections
WHERE code = $1 AND client_id = $2
`

type ConnectionFindByCodeClientParams struct {
	Code     string  `db:"code"`
	ClientID *string `db:"client_id"`
}

func (q *Queries) ConnectionFindByCodeClient(ctx context.Context, arg ConnectionFindByCodeClientParams) (MsgConnection, error) {
	row := q.db.QueryRow(ctx, connectionFindByCodeClient, arg.Code, arg.ClientID)
	var i MsgConnection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const connectionFindByID = `-- name: ConnectionFindByID :one

SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at
FROM msg_connections
WHERE id = $1
`

// Queries for msg_connections.
func (q *Queries) ConnectionFindByID(ctx context.Context, id string) (MsgConnection, error) {
	row := q.db.QueryRow(ctx, connectionFindByID, id)
	var i MsgConnection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const connectionUpsert = `-- name: ConnectionUpsert :exec
INSERT INTO msg_connections
    (id, code, name, description, external_id, status, service_account_id,
     client_id, client_identifier, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    external_id = EXCLUDED.external_id,
    status = EXCLUDED.status,
    service_account_id = EXCLUDED.service_account_id,
    client_id = EXCLUDED.client_id,
    client_identifier = EXCLUDED.client_identifier,
    updated_at = EXCLUDED.updated_at
`

type ConnectionUpsertParams struct {
	ID               string    `db:"id"`
	Code             string    `db:"code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	ExternalID       *string   `db:"external_id"`
	Status           string    `db:"status"`
	ServiceAccountID string    `db:"service_account_id"`
	ClientID         *string   `db:"client_id"`
	ClientIdentifier *string   `db:"client_identifier"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
}

func (q *Queries) ConnectionUpsert(ctx context.Context, arg ConnectionUpsertParams) error {
	_, err := q.db.Exec(ctx, connectionUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ExternalID,
		arg.Status,
		arg.ServiceAccountID,
		arg.ClientID,
		arg.ClientIdentifier,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
