// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection.sql

package dbq

import (
	"context"
	"time"
)

const connectionDelete = `-- name: ConnectionDelete :exec
DELETE FROM msg_connections WHERE id = $1
`

func (q *Queries) ConnectionDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, connectionDelete, id)
	return err
}

const connectionFindAll = `-- name: ConnectionFindAll :many
SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at, application_code, source
FROM msg_connections
ORDER BY code
`

func (q *Queries) ConnectionFindAll(ctx context.Context) ([]MsgConnection, error) {
	rows, err := q.db.Query(ctx, connectionFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgConnection{}
	for rows.Next() {
		var i MsgConnection
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.Status,
			&i.ServiceAccountID,
			&i.ClientID,
			&i.ClientIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationCode,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionFindByCode = `-- name: ConnectionFindByCode :one
SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at, application_code, source
FROM msg_connections
WHERE code = $1
  AND application_code IS NOT DISTINCT FROM $2
  AND client_id IS NOT DISTINCT FROM $3
`

type ConnectionFindByCodeParams struct {
	Code            string  `db:"code"`
	ApplicationCode *string `db:"application_code"`
	ClientID        *string `db:"client_id"`
}

// NULL-as-a-value semantics on both nullable parts of the key: a caller
// asking for "no application" (application_code = NULL) or "no client"
// (client_id = NULL) must match rows stored with NULL there, which plain
// `=` never does. Mirrors uq_msg_connections_app_client_code (migration 056).
func (q *Queries) ConnectionFindByCode(ctx context.Context, arg ConnectionFindByCodeParams) (MsgConnection, error) {
	row := q.db.QueryRow(ctx, connectionFindByCode, arg.Code, arg.ApplicationCode, arg.ClientID)
	var i MsgConnection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationCode,
		&i.Source,
	)
	return i, err
}

const connectionFindByID = `-- name: ConnectionFindByID :one

SELECT id, code, name, description, external_id, status, service_account_id,
       client_id, client_identifier, created_at, updated_at, application_code, source
FROM msg_connections
WHERE id = $1
`

// Queries for msg_connections. Column lists are kept in the table's
// physical column order (application_code/source were appended by migration
// 056) so sqlc maps every query onto the shared MsgConnection model instead
// of minting a one-off row type per query.
func (q *Queries) ConnectionFindByID(ctx context.Context, id string) (MsgConnection, error) {
	row := q.db.QueryRow(ctx, connectionFindByID, id)
	var i MsgConnection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.Status,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationCode,
		&i.Source,
	)
	return i, err
}

const connectionUpsert = `-- name: ConnectionUpsert :exec
INSERT INTO msg_connections
    (id, code, name, description, external_id, status, service_account_id,
     client_id, client_identifier, created_at, updated_at, application_code, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    external_id = EXCLUDED.external_id,
    status = EXCLUDED.status,
    service_account_id = EXCLUDED.service_account_id,
    client_id = EXCLUDED.client_id,
    client_identifier = EXCLUDED.client_identifier,
    updated_at = EXCLUDED.updated_at,
    application_code = EXCLUDED.application_code,
    source = EXCLUDED.source
`

type ConnectionUpsertParams struct {
	ID               string    `db:"id"`
	Code             string    `db:"code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	ExternalID       *string   `db:"external_id"`
	Status           string    `db:"status"`
	ServiceAccountID string    `db:"service_account_id"`
	ClientID         *string   `db:"client_id"`
	ClientIdentifier *string   `db:"client_identifier"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
	ApplicationCode  *string   `db:"application_code"`
	Source           string    `db:"source"`
}

func (q *Queries) ConnectionUpsert(ctx context.Context, arg ConnectionUpsertParams) error {
	_, err := q.db.Exec(ctx, connectionUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ExternalID,
		arg.Status,
		arg.ServiceAccountID,
		arg.ClientID,
		arg.ClientIdentifier,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ApplicationCode,
		arg.Source,
	)
	return err
}
