// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cors.sql

package dbq

import (
	"context"
	"time"
)

const corsOriginDelete = `-- name: CorsOriginDelete :exec
DELETE FROM tnt_cors_allowed_origins WHERE id = $1
`

func (q *Queries) CorsOriginDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, corsOriginDelete, id)
	return err
}

const corsOriginFindAll = `-- name: CorsOriginFindAll :many
SELECT id, origin, description, created_by, created_at, updated_at
FROM tnt_cors_allowed_origins
ORDER BY origin
`

func (q *Queries) CorsOriginFindAll(ctx context.Context) ([]TntCorsAllowedOrigin, error) {
	rows, err := q.db.Query(ctx, corsOriginFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TntCorsAllowedOrigin{}
	for rows.Next() {
		var i TntCorsAllowedOrigin
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const corsOriginFindByID = `-- name: CorsOriginFindByID :one

SELECT id, origin, description, created_by, created_at, updated_at
FROM tnt_cors_allowed_origins
WHERE id = $1
`

// Queries for tnt_cors_allowed_origins. Simple single-table CRUD.
func (q *Queries) CorsOriginFindByID(ctx context.Context, id string) (TntCorsAllowedOrigin, error) {
	row := q.db.QueryRow(ctx, corsOriginFindByID, id)
	var i TntCorsAllowedOrigin
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const corsOriginFindByOrigin = `-- name: CorsOriginFindByOrigin :one
SELECT id, origin, description, created_by, created_at, updated_at
FROM tnt_cors_allowed_origins
WHERE origin = $1
`

func (q *Queries) CorsOriginFindByOrigin(ctx context.Context, origin string) (TntCorsAllowedOrigin, error) {
	row := q.db.QueryRow(ctx, corsOriginFindByOrigin, origin)
	var i TntCorsAllowedOrigin
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const corsOriginListStrings = `-- name: CorsOriginListStrings :many
SELECT origin FROM tnt_cors_allowed_origins
`

func (q *Queries) CorsOriginListStrings(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, corsOriginListStrings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var origin string
		if err := rows.Scan(&origin); err != nil {
			return nil, err
		}
		items = append(items, origin)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const corsOriginUpsert = `-- name: CorsOriginUpsert :exec
INSERT INTO tnt_cors_allowed_origins
    (id, origin, description, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    origin = EXCLUDED.origin,
    description = EXCLUDED.description,
    updated_at = EXCLUDED.updated_at
`

type CorsOriginUpsertParams struct {
	ID          string    `db:"id"`
	Origin      string    `db:"origin"`
	Description *string   `db:"description"`
	CreatedBy   *string   `db:"created_by"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

func (q *Queries) CorsOriginUpsert(ctx context.Context, arg CorsOriginUpsertParams) error {
	_, err := q.db.Exec(ctx, corsOriginUpsert,
		arg.ID,
		arg.Origin,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
