// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatchjob.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const dispatchJobAttemptInsert = `-- name: DispatchJobAttemptInsert :exec
INSERT INTO msg_dispatch_job_attempts
    (id, dispatch_job_id, attempt_number, status, response_code,
     response_body, error_message, error_type, duration_millis,
     attempted_at, completed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type DispatchJobAttemptInsertParams struct {
	ID             string
	DispatchJobID  string
	AttemptNumber  *int32
	Status         *string
	ResponseCode   *int32
	ResponseBody   *string
	ErrorMessage   *string
	ErrorType      *string
	DurationMillis *int64
	AttemptedAt    *time.Time
	CompletedAt    *time.Time
	CreatedAt      time.Time
}

// One row per delivery attempt. The schema column `status` stores the
// attempt outcome (`SUCCESS` / `FAILURE`); the entity exposes a
// derived `success` bool to match the Rust wire shape.
func (q *Queries) DispatchJobAttemptInsert(ctx context.Context, arg DispatchJobAttemptInsertParams) error {
	_, err := q.db.Exec(ctx, dispatchJobAttemptInsert,
		arg.ID,
		arg.DispatchJobID,
		arg.AttemptNumber,
		arg.Status,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.ErrorType,
		arg.DurationMillis,
		arg.AttemptedAt,
		arg.CompletedAt,
		arg.CreatedAt,
	)
	return err
}

const dispatchJobAttemptsByJob = `-- name: DispatchJobAttemptsByJob :many
SELECT attempt_number, attempted_at, completed_at, duration_millis,
       response_code, response_body, status, error_message, error_type
FROM msg_dispatch_job_attempts
WHERE dispatch_job_id = $1
ORDER BY attempt_number ASC
`

type DispatchJobAttemptsByJobRow struct {
	AttemptNumber  *int32
	AttemptedAt    *time.Time
	CompletedAt    *time.Time
	DurationMillis *int64
	ResponseCode   *int32
	ResponseBody   *string
	Status         *string
	ErrorMessage   *string
	ErrorType      *string
}

func (q *Queries) DispatchJobAttemptsByJob(ctx context.Context, dispatchJobID string) ([]DispatchJobAttemptsByJobRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobAttemptsByJob, dispatchJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobAttemptsByJobRow{}
	for rows.Next() {
		var i DispatchJobAttemptsByJobRow
		if err := rows.Scan(
			&i.AttemptNumber,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Status,
			&i.ErrorMessage,
			&i.ErrorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobFindByEventID = `-- name: DispatchJobFindByEventID :many
SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       created_at, updated_at
FROM msg_dispatch_jobs
WHERE event_id = $1
ORDER BY created_at
`

type DispatchJobFindByEventIDRow struct {
	ID                 string
	ExternalID         *string
	Source             *string
	Kind               string
	Code               string
	Subject            *string
	EventID            *string
	CorrelationID      *string
	Metadata           json.RawMessage
	TargetUrl          string
	Protocol           string
	Payload            *string
	PayloadContentType *string
	DataOnly           bool
	ServiceAccountID   *string
	ClientID           *string
	SubscriptionID     *string
	Mode               string
	DispatchPoolID     *string
	MessageGroup       *string
	Sequence           int32
	TimeoutSeconds     int32
	SchemaID           *string
	Status             string
	MaxRetries         int32
	RetryStrategy      *string
	ScheduledFor       *time.Time
	ExpiresAt          *time.Time
	AttemptCount       int32
	LastAttemptAt      *time.Time
	CompletedAt        *time.Time
	DurationMillis     *int64
	LastError          *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) DispatchJobFindByEventID(ctx context.Context, eventID *string) ([]DispatchJobFindByEventIDRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobFindByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobFindByEventIDRow{}
	for rows.Next() {
		var i DispatchJobFindByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Kind,
			&i.Code,
			&i.Subject,
			&i.EventID,
			&i.CorrelationID,
			&i.Metadata,
			&i.TargetUrl,
			&i.Protocol,
			&i.Payload,
			&i.PayloadContentType,
			&i.DataOnly,
			&i.ServiceAccountID,
			&i.ClientID,
			&i.SubscriptionID,
			&i.Mode,
			&i.DispatchPoolID,
			&i.MessageGroup,
			&i.Sequence,
			&i.TimeoutSeconds,
			&i.SchemaID,
			&i.Status,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.ScheduledFor,
			&i.ExpiresAt,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.LastError,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobFindByExternalID = `-- name: DispatchJobFindByExternalID :one
SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       created_at, updated_at
FROM msg_dispatch_jobs
WHERE external_id = $1
`

type DispatchJobFindByExternalIDRow struct {
	ID                 string
	ExternalID         *string
	Source             *string
	Kind               string
	Code               string
	Subject            *string
	EventID            *string
	CorrelationID      *string
	Metadata           json.RawMessage
	TargetUrl          string
	Protocol           string
	Payload            *string
	PayloadContentType *string
	DataOnly           bool
	ServiceAccountID   *string
	ClientID           *string
	SubscriptionID     *string
	Mode               string
	DispatchPoolID     *string
	MessageGroup       *string
	Sequence           int32
	TimeoutSeconds     int32
	SchemaID           *string
	Status             string
	MaxRetries         int32
	RetryStrategy      *string
	ScheduledFor       *time.Time
	ExpiresAt          *time.Time
	AttemptCount       int32
	LastAttemptAt      *time.Time
	CompletedAt        *time.Time
	DurationMillis     *int64
	LastError          *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) DispatchJobFindByExternalID(ctx context.Context, externalID *string) (DispatchJobFindByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, dispatchJobFindByExternalID, externalID)
	var i DispatchJobFindByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Kind,
		&i.Code,
		&i.Subject,
		&i.EventID,
		&i.CorrelationID,
		&i.Metadata,
		&i.TargetUrl,
		&i.Protocol,
		&i.Payload,
		&i.PayloadContentType,
		&i.DataOnly,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.Mode,
		&i.DispatchPoolID,
		&i.MessageGroup,
		&i.Sequence,
		&i.TimeoutSeconds,
		&i.SchemaID,
		&i.Status,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.ScheduledFor,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DurationMillis,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchJobFindByID = `-- name: DispatchJobFindByID :one

SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       created_at, updated_at
FROM msg_dispatch_jobs
WHERE id = $1
`

type DispatchJobFindByIDRow struct {
	ID                 string
	ExternalID         *string
	Source             *string
	Kind               string
	Code               string
	Subject            *string
	EventID            *string
	CorrelationID      *string
	Metadata           json.RawMessage
	TargetUrl          string
	Protocol           string
	Payload            *string
	PayloadContentType *string
	DataOnly           bool
	ServiceAccountID   *string
	ClientID           *string
	SubscriptionID     *string
	Mode               string
	DispatchPoolID     *string
	MessageGroup       *string
	Sequence           int32
	TimeoutSeconds     int32
	SchemaID           *string
	Status             string
	MaxRetries         int32
	RetryStrategy      *string
	ScheduledFor       *time.Time
	ExpiresAt          *time.Time
	AttemptCount       int32
	LastAttemptAt      *time.Time
	CompletedAt        *time.Time
	DurationMillis     *int64
	LastError          *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Queries for msg_dispatch_jobs + msg_dispatch_job_attempts. The
// column set matches the post-019 (partitioned) schema. Composite PK
// is (id, created_at); claim queries use FOR UPDATE SKIP LOCKED so
// multiple scheduler nodes can run against the same DB without
// contention.
//
// FindWithFilters + DistinctValues stay hand-rolled in repository.go
// (dynamic WHERE + dynamic column names) — sqlc can't generate those
// without a query per filter combination.
//
// InsertBatch also stays in repository.go via pgx.Batch — sqlc has no
// batch wrapper for partial-failure-tolerant UNNEST inserts.
func (q *Queries) DispatchJobFindByID(ctx context.Context, id string) (DispatchJobFindByIDRow, error) {
	row := q.db.QueryRow(ctx, dispatchJobFindByID, id)
	var i DispatchJobFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Kind,
		&i.Code,
		&i.Subject,
		&i.EventID,
		&i.CorrelationID,
		&i.Metadata,
		&i.TargetUrl,
		&i.Protocol,
		&i.Payload,
		&i.PayloadContentType,
		&i.DataOnly,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.Mode,
		&i.DispatchPoolID,
		&i.MessageGroup,
		&i.Sequence,
		&i.TimeoutSeconds,
		&i.SchemaID,
		&i.Status,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.ScheduledFor,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DurationMillis,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchJobFindPendingForPool = `-- name: DispatchJobFindPendingForPool :many
SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       created_at, updated_at
FROM msg_dispatch_jobs
WHERE status = 'PENDING'
  AND dispatch_pool_id = $1
  AND (scheduled_for IS NULL OR scheduled_for <= NOW())
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type DispatchJobFindPendingForPoolParams struct {
	DispatchPoolID *string
	Limit          int32
}

type DispatchJobFindPendingForPoolRow struct {
	ID                 string
	ExternalID         *string
	Source             *string
	Kind               string
	Code               string
	Subject            *string
	EventID            *string
	CorrelationID      *string
	Metadata           json.RawMessage
	TargetUrl          string
	Protocol           string
	Payload            *string
	PayloadContentType *string
	DataOnly           bool
	ServiceAccountID   *string
	ClientID           *string
	SubscriptionID     *string
	Mode               string
	DispatchPoolID     *string
	MessageGroup       *string
	Sequence           int32
	TimeoutSeconds     int32
	SchemaID           *string
	Status             string
	MaxRetries         int32
	RetryStrategy      *string
	ScheduledFor       *time.Time
	ExpiresAt          *time.Time
	AttemptCount       int32
	LastAttemptAt      *time.Time
	CompletedAt        *time.Time
	DurationMillis     *int64
	LastError          *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Used by the scheduler's PendingJobPoller. FOR UPDATE SKIP LOCKED so
// the claim works concurrently across scheduler nodes. Filter on
// scheduled_for skips retries not yet due.
func (q *Queries) DispatchJobFindPendingForPool(ctx context.Context, arg DispatchJobFindPendingForPoolParams) ([]DispatchJobFindPendingForPoolRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobFindPendingForPool, arg.DispatchPoolID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobFindPendingForPoolRow{}
	for rows.Next() {
		var i DispatchJobFindPendingForPoolRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Kind,
			&i.Code,
			&i.Subject,
			&i.EventID,
			&i.CorrelationID,
			&i.Metadata,
			&i.TargetUrl,
			&i.Protocol,
			&i.Payload,
			&i.PayloadContentType,
			&i.DataOnly,
			&i.ServiceAccountID,
			&i.ClientID,
			&i.SubscriptionID,
			&i.Mode,
			&i.DispatchPoolID,
			&i.MessageGroup,
			&i.Sequence,
			&i.TimeoutSeconds,
			&i.SchemaID,
			&i.Status,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.ScheduledFor,
			&i.ExpiresAt,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.LastError,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobInsert = `-- name: DispatchJobInsert :exec
INSERT INTO msg_dispatch_jobs
    (id, external_id, source, kind, code, subject, event_id, correlation_id,
     metadata, target_url, protocol, payload, payload_content_type, data_only,
     service_account_id, client_id, subscription_id, mode, dispatch_pool_id,
     message_group, sequence, timeout_seconds, schema_id, status, max_retries,
     retry_strategy, scheduled_for, expires_at, attempt_count, last_attempt_at,
     completed_at, duration_millis, last_error, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
        $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26,
        $27, $28, $29, $30, $31, $32, $33, $34, $35, $36)
`

type DispatchJobInsertParams struct {
	ID                 string
	ExternalID         *string
	Source             *string
	Kind               string
	Code               string
	Subject            *string
	EventID            *string
	CorrelationID      *string
	Metadata           json.RawMessage
	TargetUrl          string
	Protocol           string
	Payload            *string
	PayloadContentType *string
	DataOnly           bool
	ServiceAccountID   *string
	ClientID           *string
	SubscriptionID     *string
	Mode               string
	DispatchPoolID     *string
	MessageGroup       *string
	Sequence           int32
	TimeoutSeconds     int32
	SchemaID           *string
	Status             string
	MaxRetries         int32
	RetryStrategy      *string
	ScheduledFor       *time.Time
	ExpiresAt          *time.Time
	AttemptCount       int32
	LastAttemptAt      *time.Time
	CompletedAt        *time.Time
	DurationMillis     *int64
	LastError          *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) DispatchJobInsert(ctx context.Context, arg DispatchJobInsertParams) error {
	_, err := q.db.Exec(ctx, dispatchJobInsert,
		arg.ID,
		arg.ExternalID,
		arg.Source,
		arg.Kind,
		arg.Code,
		arg.Subject,
		arg.EventID,
		arg.CorrelationID,
		arg.Metadata,
		arg.TargetUrl,
		arg.Protocol,
		arg.Payload,
		arg.PayloadContentType,
		arg.DataOnly,
		arg.ServiceAccountID,
		arg.ClientID,
		arg.SubscriptionID,
		arg.Mode,
		arg.DispatchPoolID,
		arg.MessageGroup,
		arg.Sequence,
		arg.TimeoutSeconds,
		arg.SchemaID,
		arg.Status,
		arg.MaxRetries,
		arg.RetryStrategy,
		arg.ScheduledFor,
		arg.ExpiresAt,
		arg.AttemptCount,
		arg.LastAttemptAt,
		arg.CompletedAt,
		arg.DurationMillis,
		arg.LastError,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const dispatchJobMarkCompleted = `-- name: DispatchJobMarkCompleted :exec
UPDATE msg_dispatch_jobs
   SET status = 'COMPLETED',
       completed_at = $2,
       duration_millis = $3,
       updated_at = $2
 WHERE id = $1
`

type DispatchJobMarkCompletedParams struct {
	ID             string
	CompletedAt    *time.Time
	DurationMillis *int64
}

// Status → COMPLETED. Stamps completed_at + duration_millis.
func (q *Queries) DispatchJobMarkCompleted(ctx context.Context, arg DispatchJobMarkCompletedParams) error {
	_, err := q.db.Exec(ctx, dispatchJobMarkCompleted, arg.ID, arg.CompletedAt, arg.DurationMillis)
	return err
}

const dispatchJobMarkFailed = `-- name: DispatchJobMarkFailed :exec
UPDATE msg_dispatch_jobs
   SET status = 'FAILED',
       completed_at = $2,
       duration_millis = $3,
       last_error = $4,
       updated_at = $2
 WHERE id = $1
`

type DispatchJobMarkFailedParams struct {
	ID             string
	CompletedAt    *time.Time
	DurationMillis *int64
	LastError      *string
}

// Terminal failure. Stamps last_error + completed_at + duration_millis.
func (q *Queries) DispatchJobMarkFailed(ctx context.Context, arg DispatchJobMarkFailedParams) error {
	_, err := q.db.Exec(ctx, dispatchJobMarkFailed,
		arg.ID,
		arg.CompletedAt,
		arg.DurationMillis,
		arg.LastError,
	)
	return err
}

const dispatchJobMarkInProgress = `-- name: DispatchJobMarkInProgress :exec
UPDATE msg_dispatch_jobs
   SET status = 'PROCESSING',
       last_attempt_at = $2,
       updated_at = $2
 WHERE id = $1
`

type DispatchJobMarkInProgressParams struct {
	ID            string
	LastAttemptAt *time.Time
}

// Status → PROCESSING. Stamps last_attempt_at. Called by the router
// immediately before the first delivery attempt.
func (q *Queries) DispatchJobMarkInProgress(ctx context.Context, arg DispatchJobMarkInProgressParams) error {
	_, err := q.db.Exec(ctx, dispatchJobMarkInProgress, arg.ID, arg.LastAttemptAt)
	return err
}

const dispatchJobScheduleRetry = `-- name: DispatchJobScheduleRetry :exec
UPDATE msg_dispatch_jobs
   SET attempt_count = attempt_count + 1,
       scheduled_for = $2,
       last_error = $3,
       last_attempt_at = NOW(),
       status = 'PENDING',
       updated_at = NOW()
 WHERE id = $1
`

type DispatchJobScheduleRetryParams struct {
	ID           string
	ScheduledFor *time.Time
	LastError    *string
}

// Bumps attempt_count + stamps scheduled_for so the next poll picks
// it up once due. Status stays PENDING.
func (q *Queries) DispatchJobScheduleRetry(ctx context.Context, arg DispatchJobScheduleRetryParams) error {
	_, err := q.db.Exec(ctx, dispatchJobScheduleRetry, arg.ID, arg.ScheduledFor, arg.LastError)
	return err
}
