// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatchjob.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const dispatchJobAttemptInsert = `-- name: DispatchJobAttemptInsert :exec
INSERT INTO msg_dispatch_job_attempts
    (id, dispatch_job_id, attempt_number, status, response_code,
     response_body, error_message, error_type, duration_millis,
     attempted_at, completed_at, created_at, request_info)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type DispatchJobAttemptInsertParams struct {
	ID             string          `db:"id"`
	DispatchJobID  string          `db:"dispatch_job_id"`
	AttemptNumber  *int32          `db:"attempt_number"`
	Status         *string         `db:"status"`
	ResponseCode   *int32          `db:"response_code"`
	ResponseBody   *string         `db:"response_body"`
	ErrorMessage   *string         `db:"error_message"`
	ErrorType      *string         `db:"error_type"`
	DurationMillis *int64          `db:"duration_millis"`
	AttemptedAt    *time.Time      `db:"attempted_at"`
	CompletedAt    *time.Time      `db:"completed_at"`
	CreatedAt      time.Time       `db:"created_at"`
	RequestInfo    json.RawMessage `db:"request_info"`
}

// One row per delivery attempt. The schema column `status` stores the
// attempt outcome (`SUCCESS` / `FAILURE`); the entity exposes a
// derived `success` bool to match the legacy-platform wire shape.
func (q *Queries) DispatchJobAttemptInsert(ctx context.Context, arg DispatchJobAttemptInsertParams) error {
	_, err := q.db.Exec(ctx, dispatchJobAttemptInsert,
		arg.ID,
		arg.DispatchJobID,
		arg.AttemptNumber,
		arg.Status,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.ErrorType,
		arg.DurationMillis,
		arg.AttemptedAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.RequestInfo,
	)
	return err
}

const dispatchJobAttemptsByJob = `-- name: DispatchJobAttemptsByJob :many
SELECT attempt_number, attempted_at, completed_at, duration_millis,
       response_code, response_body, status, error_message, error_type,
       request_info
FROM msg_dispatch_job_attempts
WHERE dispatch_job_id = $1
ORDER BY attempted_at ASC, attempt_number ASC
`

type DispatchJobAttemptsByJobRow struct {
	AttemptNumber  *int32          `db:"attempt_number"`
	AttemptedAt    *time.Time      `db:"attempted_at"`
	CompletedAt    *time.Time      `db:"completed_at"`
	DurationMillis *int64          `db:"duration_millis"`
	ResponseCode   *int32          `db:"response_code"`
	ResponseBody   *string         `db:"response_body"`
	Status         *string         `db:"status"`
	ErrorMessage   *string         `db:"error_message"`
	ErrorType      *string         `db:"error_type"`
	RequestInfo    json.RawMessage `db:"request_info"`
}

// Chronological, not by attempt_number: a requeue starts a new run whose
// attempts are numbered from 1 again, so ordering by number interleaves
// runs. attempted_at is the order an operator reads them in.
func (q *Queries) DispatchJobAttemptsByJob(ctx context.Context, dispatchJobID string) ([]DispatchJobAttemptsByJobRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobAttemptsByJob, dispatchJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobAttemptsByJobRow{}
	for rows.Next() {
		var i DispatchJobAttemptsByJobRow
		if err := rows.Scan(
			&i.AttemptNumber,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Status,
			&i.ErrorMessage,
			&i.ErrorType,
			&i.RequestInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobFindByID = `-- name: DispatchJobFindByID :one

SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       queue, descriptor, created_at, updated_at
FROM msg_dispatch_jobs
WHERE id = $1
`

type DispatchJobFindByIDRow struct {
	ID                 string          `db:"id"`
	ExternalID         *string         `db:"external_id"`
	Source             *string         `db:"source"`
	Kind               string          `db:"kind"`
	Code               string          `db:"code"`
	Subject            *string         `db:"subject"`
	EventID            *string         `db:"event_id"`
	CorrelationID      *string         `db:"correlation_id"`
	Metadata           json.RawMessage `db:"metadata"`
	TargetUrl          string          `db:"target_url"`
	Protocol           string          `db:"protocol"`
	Payload            *string         `db:"payload"`
	PayloadContentType *string         `db:"payload_content_type"`
	DataOnly           bool            `db:"data_only"`
	ServiceAccountID   *string         `db:"service_account_id"`
	ClientID           *string         `db:"client_id"`
	SubscriptionID     *string         `db:"subscription_id"`
	Mode               string          `db:"mode"`
	DispatchPoolID     *string         `db:"dispatch_pool_id"`
	MessageGroup       *string         `db:"message_group"`
	Sequence           int32           `db:"sequence"`
	TimeoutSeconds     int32           `db:"timeout_seconds"`
	SchemaID           *string         `db:"schema_id"`
	Status             string          `db:"status"`
	MaxRetries         int32           `db:"max_retries"`
	RetryStrategy      *string         `db:"retry_strategy"`
	ScheduledFor       *time.Time      `db:"scheduled_for"`
	ExpiresAt          *time.Time      `db:"expires_at"`
	AttemptCount       int32           `db:"attempt_count"`
	LastAttemptAt      *time.Time      `db:"last_attempt_at"`
	CompletedAt        *time.Time      `db:"completed_at"`
	DurationMillis     *int64          `db:"duration_millis"`
	LastError          *string         `db:"last_error"`
	IdempotencyKey     *string         `db:"idempotency_key"`
	Queue              *string         `db:"queue"`
	Descriptor         *string         `db:"descriptor"`
	CreatedAt          time.Time       `db:"created_at"`
	UpdatedAt          time.Time       `db:"updated_at"`
}

// Read queries for msg_dispatch_jobs + the attempts table. The column set
// matches the post-019 (partitioned) schema. Composite PK is (id, created_at).
//
// msg_dispatch_jobs is WRITTEN only by the dispatch-job lifecycle
// (internal/platform/dispatchjob/lifecycle.go): every insert and every status
// transition is hand-built there, over whatever pool or transaction the caller
// passes, so it carries no sqlc query. Nothing in this file may INSERT, UPDATE
// or DELETE msg_dispatch_jobs (lifecycle_enforce_test.go checks).
//
// FindWithFilters + DistinctValues stay hand-rolled in repository.go
// (dynamic WHERE + dynamic column names).
func (q *Queries) DispatchJobFindByID(ctx context.Context, id string) (DispatchJobFindByIDRow, error) {
	row := q.db.QueryRow(ctx, dispatchJobFindByID, id)
	var i DispatchJobFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Kind,
		&i.Code,
		&i.Subject,
		&i.EventID,
		&i.CorrelationID,
		&i.Metadata,
		&i.TargetUrl,
		&i.Protocol,
		&i.Payload,
		&i.PayloadContentType,
		&i.DataOnly,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.Mode,
		&i.DispatchPoolID,
		&i.MessageGroup,
		&i.Sequence,
		&i.TimeoutSeconds,
		&i.SchemaID,
		&i.Status,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.ScheduledFor,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DurationMillis,
		&i.LastError,
		&i.IdempotencyKey,
		&i.Queue,
		&i.Descriptor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchJobFindByIDs = `-- name: DispatchJobFindByIDs :many
SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       queue, descriptor, created_at, updated_at
FROM msg_dispatch_jobs
WHERE id = ANY($1::text[])
`

type DispatchJobFindByIDsRow struct {
	ID                 string          `db:"id"`
	ExternalID         *string         `db:"external_id"`
	Source             *string         `db:"source"`
	Kind               string          `db:"kind"`
	Code               string          `db:"code"`
	Subject            *string         `db:"subject"`
	EventID            *string         `db:"event_id"`
	CorrelationID      *string         `db:"correlation_id"`
	Metadata           json.RawMessage `db:"metadata"`
	TargetUrl          string          `db:"target_url"`
	Protocol           string          `db:"protocol"`
	Payload            *string         `db:"payload"`
	PayloadContentType *string         `db:"payload_content_type"`
	DataOnly           bool            `db:"data_only"`
	ServiceAccountID   *string         `db:"service_account_id"`
	ClientID           *string         `db:"client_id"`
	SubscriptionID     *string         `db:"subscription_id"`
	Mode               string          `db:"mode"`
	DispatchPoolID     *string         `db:"dispatch_pool_id"`
	MessageGroup       *string         `db:"message_group"`
	Sequence           int32           `db:"sequence"`
	TimeoutSeconds     int32           `db:"timeout_seconds"`
	SchemaID           *string         `db:"schema_id"`
	Status             string          `db:"status"`
	MaxRetries         int32           `db:"max_retries"`
	RetryStrategy      *string         `db:"retry_strategy"`
	ScheduledFor       *time.Time      `db:"scheduled_for"`
	ExpiresAt          *time.Time      `db:"expires_at"`
	AttemptCount       int32           `db:"attempt_count"`
	LastAttemptAt      *time.Time      `db:"last_attempt_at"`
	CompletedAt        *time.Time      `db:"completed_at"`
	DurationMillis     *int64          `db:"duration_millis"`
	LastError          *string         `db:"last_error"`
	IdempotencyKey     *string         `db:"idempotency_key"`
	Queue              *string         `db:"queue"`
	Descriptor         *string         `db:"descriptor"`
	CreatedAt          time.Time       `db:"created_at"`
	UpdatedAt          time.Time       `db:"updated_at"`
}

// Batch load by id (write table), for the Resend operation, which reloads
// multiple aggregates to reset via usecaseop.SaveAll.
func (q *Queries) DispatchJobFindByIDs(ctx context.Context, ids []string) ([]DispatchJobFindByIDsRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobFindByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobFindByIDsRow{}
	for rows.Next() {
		var i DispatchJobFindByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Kind,
			&i.Code,
			&i.Subject,
			&i.EventID,
			&i.CorrelationID,
			&i.Metadata,
			&i.TargetUrl,
			&i.Protocol,
			&i.Payload,
			&i.PayloadContentType,
			&i.DataOnly,
			&i.ServiceAccountID,
			&i.ClientID,
			&i.SubscriptionID,
			&i.Mode,
			&i.DispatchPoolID,
			&i.MessageGroup,
			&i.Sequence,
			&i.TimeoutSeconds,
			&i.SchemaID,
			&i.Status,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.ScheduledFor,
			&i.ExpiresAt,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.LastError,
			&i.IdempotencyKey,
			&i.Queue,
			&i.Descriptor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
