// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatchjob.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const dispatchJobAttemptInsert = `-- name: DispatchJobAttemptInsert :exec
INSERT INTO msg_dispatch_job_attempts
    (id, dispatch_job_id, attempt_number, status, response_code,
     response_body, error_message, error_type, duration_millis,
     attempted_at, completed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type DispatchJobAttemptInsertParams struct {
	ID             string     `db:"id"`
	DispatchJobID  string     `db:"dispatch_job_id"`
	AttemptNumber  *int32     `db:"attempt_number"`
	Status         *string    `db:"status"`
	ResponseCode   *int32     `db:"response_code"`
	ResponseBody   *string    `db:"response_body"`
	ErrorMessage   *string    `db:"error_message"`
	ErrorType      *string    `db:"error_type"`
	DurationMillis *int64     `db:"duration_millis"`
	AttemptedAt    *time.Time `db:"attempted_at"`
	CompletedAt    *time.Time `db:"completed_at"`
	CreatedAt      time.Time  `db:"created_at"`
}

// One row per delivery attempt. The schema column `status` stores the
// attempt outcome (`SUCCESS` / `FAILURE`); the entity exposes a
// derived `success` bool to match the legacy-platform wire shape.
func (q *Queries) DispatchJobAttemptInsert(ctx context.Context, arg DispatchJobAttemptInsertParams) error {
	_, err := q.db.Exec(ctx, dispatchJobAttemptInsert,
		arg.ID,
		arg.DispatchJobID,
		arg.AttemptNumber,
		arg.Status,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.ErrorType,
		arg.DurationMillis,
		arg.AttemptedAt,
		arg.CompletedAt,
		arg.CreatedAt,
	)
	return err
}

const dispatchJobAttemptsByJob = `-- name: DispatchJobAttemptsByJob :many
SELECT attempt_number, attempted_at, completed_at, duration_millis,
       response_code, response_body, status, error_message, error_type
FROM msg_dispatch_job_attempts
WHERE dispatch_job_id = $1
ORDER BY attempt_number ASC
`

type DispatchJobAttemptsByJobRow struct {
	AttemptNumber  *int32     `db:"attempt_number"`
	AttemptedAt    *time.Time `db:"attempted_at"`
	CompletedAt    *time.Time `db:"completed_at"`
	DurationMillis *int64     `db:"duration_millis"`
	ResponseCode   *int32     `db:"response_code"`
	ResponseBody   *string    `db:"response_body"`
	Status         *string    `db:"status"`
	ErrorMessage   *string    `db:"error_message"`
	ErrorType      *string    `db:"error_type"`
}

func (q *Queries) DispatchJobAttemptsByJob(ctx context.Context, dispatchJobID string) ([]DispatchJobAttemptsByJobRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobAttemptsByJob, dispatchJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobAttemptsByJobRow{}
	for rows.Next() {
		var i DispatchJobAttemptsByJobRow
		if err := rows.Scan(
			&i.AttemptNumber,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.Status,
			&i.ErrorMessage,
			&i.ErrorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobDelete = `-- name: DispatchJobDelete :exec
DELETE FROM msg_dispatch_jobs WHERE id = $1 AND created_at = $2
`

type DispatchJobDeleteParams struct {
	ID        string    `db:"id"`
	CreatedAt time.Time `db:"created_at"`
}

// Satisfies usecasepgx.Persist[DispatchJob], which requires both Persist
// and Delete. No operation in this module deletes a dispatch job today
// (Cancel/Complete/Resend all use Save/SaveAll), so this exists purely for
// interface conformance — but it's a real delete, not a stub, in case that
// ever changes.
func (q *Queries) DispatchJobDelete(ctx context.Context, arg DispatchJobDeleteParams) error {
	_, err := q.db.Exec(ctx, dispatchJobDelete, arg.ID, arg.CreatedAt)
	return err
}

const dispatchJobFindByID = `-- name: DispatchJobFindByID :one

SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       created_at, updated_at
FROM msg_dispatch_jobs
WHERE id = $1
`

type DispatchJobFindByIDRow struct {
	ID                 string          `db:"id"`
	ExternalID         *string         `db:"external_id"`
	Source             *string         `db:"source"`
	Kind               string          `db:"kind"`
	Code               string          `db:"code"`
	Subject            *string         `db:"subject"`
	EventID            *string         `db:"event_id"`
	CorrelationID      *string         `db:"correlation_id"`
	Metadata           json.RawMessage `db:"metadata"`
	TargetUrl          string          `db:"target_url"`
	Protocol           string          `db:"protocol"`
	Payload            *string         `db:"payload"`
	PayloadContentType *string         `db:"payload_content_type"`
	DataOnly           bool            `db:"data_only"`
	ServiceAccountID   *string         `db:"service_account_id"`
	ClientID           *string         `db:"client_id"`
	SubscriptionID     *string         `db:"subscription_id"`
	Mode               string          `db:"mode"`
	DispatchPoolID     *string         `db:"dispatch_pool_id"`
	MessageGroup       *string         `db:"message_group"`
	Sequence           int32           `db:"sequence"`
	TimeoutSeconds     int32           `db:"timeout_seconds"`
	SchemaID           *string         `db:"schema_id"`
	Status             string          `db:"status"`
	MaxRetries         int32           `db:"max_retries"`
	RetryStrategy      *string         `db:"retry_strategy"`
	ScheduledFor       *time.Time      `db:"scheduled_for"`
	ExpiresAt          *time.Time      `db:"expires_at"`
	AttemptCount       int32           `db:"attempt_count"`
	LastAttemptAt      *time.Time      `db:"last_attempt_at"`
	CompletedAt        *time.Time      `db:"completed_at"`
	DurationMillis     *int64          `db:"duration_millis"`
	LastError          *string         `db:"last_error"`
	IdempotencyKey     *string         `db:"idempotency_key"`
	CreatedAt          time.Time       `db:"created_at"`
	UpdatedAt          time.Time       `db:"updated_at"`
}

// Queries for msg_dispatch_jobs + msg_dispatch_job_attempts. The
// column set matches the post-019 (partitioned) schema. Composite PK
// is (id, created_at); claim queries use FOR UPDATE SKIP LOCKED so
// multiple scheduler nodes can run against the same DB without
// contention.
//
// FindWithFilters + DistinctValues stay hand-rolled in repository.go
// (dynamic WHERE + dynamic column names) — sqlc can't generate those
// without a query per filter combination.
//
// InsertBatch also stays in repository.go via pgx.Batch — sqlc has no
// batch wrapper for partial-failure-tolerant UNNEST inserts.
func (q *Queries) DispatchJobFindByID(ctx context.Context, id string) (DispatchJobFindByIDRow, error) {
	row := q.db.QueryRow(ctx, dispatchJobFindByID, id)
	var i DispatchJobFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Kind,
		&i.Code,
		&i.Subject,
		&i.EventID,
		&i.CorrelationID,
		&i.Metadata,
		&i.TargetUrl,
		&i.Protocol,
		&i.Payload,
		&i.PayloadContentType,
		&i.DataOnly,
		&i.ServiceAccountID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.Mode,
		&i.DispatchPoolID,
		&i.MessageGroup,
		&i.Sequence,
		&i.TimeoutSeconds,
		&i.SchemaID,
		&i.Status,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.ScheduledFor,
		&i.ExpiresAt,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DurationMillis,
		&i.LastError,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchJobFindByIDs = `-- name: DispatchJobFindByIDs :many

SELECT id, external_id, source, kind, code, subject, event_id,
       correlation_id, metadata, target_url, protocol, payload,
       payload_content_type, data_only, service_account_id, client_id,
       subscription_id, mode, dispatch_pool_id, message_group, sequence,
       timeout_seconds, schema_id, status, max_retries, retry_strategy,
       scheduled_for, expires_at, attempt_count, last_attempt_at,
       completed_at, duration_millis, last_error, idempotency_key,
       created_at, updated_at
FROM msg_dispatch_jobs
WHERE id = ANY($1::text[])
`

type DispatchJobFindByIDsRow struct {
	ID                 string          `db:"id"`
	ExternalID         *string         `db:"external_id"`
	Source             *string         `db:"source"`
	Kind               string          `db:"kind"`
	Code               string          `db:"code"`
	Subject            *string         `db:"subject"`
	EventID            *string         `db:"event_id"`
	CorrelationID      *string         `db:"correlation_id"`
	Metadata           json.RawMessage `db:"metadata"`
	TargetUrl          string          `db:"target_url"`
	Protocol           string          `db:"protocol"`
	Payload            *string         `db:"payload"`
	PayloadContentType *string         `db:"payload_content_type"`
	DataOnly           bool            `db:"data_only"`
	ServiceAccountID   *string         `db:"service_account_id"`
	ClientID           *string         `db:"client_id"`
	SubscriptionID     *string         `db:"subscription_id"`
	Mode               string          `db:"mode"`
	DispatchPoolID     *string         `db:"dispatch_pool_id"`
	MessageGroup       *string         `db:"message_group"`
	Sequence           int32           `db:"sequence"`
	TimeoutSeconds     int32           `db:"timeout_seconds"`
	SchemaID           *string         `db:"schema_id"`
	Status             string          `db:"status"`
	MaxRetries         int32           `db:"max_retries"`
	RetryStrategy      *string         `db:"retry_strategy"`
	ScheduledFor       *time.Time      `db:"scheduled_for"`
	ExpiresAt          *time.Time      `db:"expires_at"`
	AttemptCount       int32           `db:"attempt_count"`
	LastAttemptAt      *time.Time      `db:"last_attempt_at"`
	CompletedAt        *time.Time      `db:"completed_at"`
	DurationMillis     *int64          `db:"duration_millis"`
	LastError          *string         `db:"last_error"`
	IdempotencyKey     *string         `db:"idempotency_key"`
	CreatedAt          time.Time       `db:"created_at"`
	UpdatedAt          time.Time       `db:"updated_at"`
}

// Queries below back T3/A-01 (BLOCK_ON_ERROR group recovery): the use-case
// envelope ops (cancel/complete/resend, internal/platform/dispatchjob/operations),
// the router-settled hook (internal/platform/dispatchjob/settled), and the
// stranded-sibling reaper (internal/platform/dispatchjob/reaper.go).
// Batch load by id (write table), for the Resend operation, which reloads
// multiple aggregates to reset via usecaseop.SaveAll.
func (q *Queries) DispatchJobFindByIDs(ctx context.Context, ids []string) ([]DispatchJobFindByIDsRow, error) {
	rows, err := q.db.Query(ctx, dispatchJobFindByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchJobFindByIDsRow{}
	for rows.Next() {
		var i DispatchJobFindByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Kind,
			&i.Code,
			&i.Subject,
			&i.EventID,
			&i.CorrelationID,
			&i.Metadata,
			&i.TargetUrl,
			&i.Protocol,
			&i.Payload,
			&i.PayloadContentType,
			&i.DataOnly,
			&i.ServiceAccountID,
			&i.ClientID,
			&i.SubscriptionID,
			&i.Mode,
			&i.DispatchPoolID,
			&i.MessageGroup,
			&i.Sequence,
			&i.TimeoutSeconds,
			&i.SchemaID,
			&i.Status,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.ScheduledFor,
			&i.ExpiresAt,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.DurationMillis,
			&i.LastError,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobInsert = `-- name: DispatchJobInsert :exec
INSERT INTO msg_dispatch_jobs
    (id, external_id, source, kind, code, subject, event_id, correlation_id,
     metadata, target_url, protocol, payload, payload_content_type, data_only,
     service_account_id, client_id, subscription_id, mode, dispatch_pool_id,
     message_group, sequence, timeout_seconds, schema_id, status, max_retries,
     retry_strategy, scheduled_for, expires_at, attempt_count, last_attempt_at,
     completed_at, duration_millis, last_error, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
        $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26,
        $27, $28, $29, $30, $31, $32, $33, $34, $35, $36)
`

type DispatchJobInsertParams struct {
	ID                 string          `db:"id"`
	ExternalID         *string         `db:"external_id"`
	Source             *string         `db:"source"`
	Kind               string          `db:"kind"`
	Code               string          `db:"code"`
	Subject            *string         `db:"subject"`
	EventID            *string         `db:"event_id"`
	CorrelationID      *string         `db:"correlation_id"`
	Metadata           json.RawMessage `db:"metadata"`
	TargetUrl          string          `db:"target_url"`
	Protocol           string          `db:"protocol"`
	Payload            *string         `db:"payload"`
	PayloadContentType *string         `db:"payload_content_type"`
	DataOnly           bool            `db:"data_only"`
	ServiceAccountID   *string         `db:"service_account_id"`
	ClientID           *string         `db:"client_id"`
	SubscriptionID     *string         `db:"subscription_id"`
	Mode               string          `db:"mode"`
	DispatchPoolID     *string         `db:"dispatch_pool_id"`
	MessageGroup       *string         `db:"message_group"`
	Sequence           int32           `db:"sequence"`
	TimeoutSeconds     int32           `db:"timeout_seconds"`
	SchemaID           *string         `db:"schema_id"`
	Status             string          `db:"status"`
	MaxRetries         int32           `db:"max_retries"`
	RetryStrategy      *string         `db:"retry_strategy"`
	ScheduledFor       *time.Time      `db:"scheduled_for"`
	ExpiresAt          *time.Time      `db:"expires_at"`
	AttemptCount       int32           `db:"attempt_count"`
	LastAttemptAt      *time.Time      `db:"last_attempt_at"`
	CompletedAt        *time.Time      `db:"completed_at"`
	DurationMillis     *int64          `db:"duration_millis"`
	LastError          *string         `db:"last_error"`
	IdempotencyKey     *string         `db:"idempotency_key"`
	CreatedAt          time.Time       `db:"created_at"`
	UpdatedAt          time.Time       `db:"updated_at"`
}

func (q *Queries) DispatchJobInsert(ctx context.Context, arg DispatchJobInsertParams) error {
	_, err := q.db.Exec(ctx, dispatchJobInsert,
		arg.ID,
		arg.ExternalID,
		arg.Source,
		arg.Kind,
		arg.Code,
		arg.Subject,
		arg.EventID,
		arg.CorrelationID,
		arg.Metadata,
		arg.TargetUrl,
		arg.Protocol,
		arg.Payload,
		arg.PayloadContentType,
		arg.DataOnly,
		arg.ServiceAccountID,
		arg.ClientID,
		arg.SubscriptionID,
		arg.Mode,
		arg.DispatchPoolID,
		arg.MessageGroup,
		arg.Sequence,
		arg.TimeoutSeconds,
		arg.SchemaID,
		arg.Status,
		arg.MaxRetries,
		arg.RetryStrategy,
		arg.ScheduledFor,
		arg.ExpiresAt,
		arg.AttemptCount,
		arg.LastAttemptAt,
		arg.CompletedAt,
		arg.DurationMillis,
		arg.LastError,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const dispatchJobMarkCompleted = `-- name: DispatchJobMarkCompleted :exec
UPDATE msg_dispatch_jobs
   SET status = 'COMPLETED',
       completed_at = $2,
       duration_millis = $3,
       updated_at = $2
 WHERE id = $1
   AND created_at = $4
`

type DispatchJobMarkCompletedParams struct {
	ID             string     `db:"id"`
	CompletedAt    *time.Time `db:"completed_at"`
	DurationMillis *int64     `db:"duration_millis"`
	CreatedAt      time.Time  `db:"created_at"`
}

// Status → COMPLETED. Stamps completed_at + duration_millis.
func (q *Queries) DispatchJobMarkCompleted(ctx context.Context, arg DispatchJobMarkCompletedParams) error {
	_, err := q.db.Exec(ctx, dispatchJobMarkCompleted,
		arg.ID,
		arg.CompletedAt,
		arg.DurationMillis,
		arg.CreatedAt,
	)
	return err
}

const dispatchJobMarkFailed = `-- name: DispatchJobMarkFailed :exec
UPDATE msg_dispatch_jobs
   SET status = 'FAILED',
       completed_at = $2,
       duration_millis = $3,
       last_error = $4,
       updated_at = $2
 WHERE id = $1
   AND created_at = $5
`

type DispatchJobMarkFailedParams struct {
	ID             string     `db:"id"`
	CompletedAt    *time.Time `db:"completed_at"`
	DurationMillis *int64     `db:"duration_millis"`
	LastError      *string    `db:"last_error"`
	CreatedAt      time.Time  `db:"created_at"`
}

// Terminal failure. Stamps last_error + completed_at + duration_millis.
func (q *Queries) DispatchJobMarkFailed(ctx context.Context, arg DispatchJobMarkFailedParams) error {
	_, err := q.db.Exec(ctx, dispatchJobMarkFailed,
		arg.ID,
		arg.CompletedAt,
		arg.DurationMillis,
		arg.LastError,
		arg.CreatedAt,
	)
	return err
}

const dispatchJobMarkInProgress = `-- name: DispatchJobMarkInProgress :exec
UPDATE msg_dispatch_jobs
   SET status = 'PROCESSING',
       last_attempt_at = $2,
       updated_at = $2
 WHERE id = $1
   AND created_at = $3
`

type DispatchJobMarkInProgressParams struct {
	ID            string     `db:"id"`
	LastAttemptAt *time.Time `db:"last_attempt_at"`
	CreatedAt     time.Time  `db:"created_at"`
}

// Status → PROCESSING. Stamps last_attempt_at. Called by the router
// immediately before the first delivery attempt.
// These status flips all carry `created_at = $N` alongside the id: the
// table is partitioned by created_at, and without it every statement
// probes every partition instead of pruning to the row's own.
func (q *Queries) DispatchJobMarkInProgress(ctx context.Context, arg DispatchJobMarkInProgressParams) error {
	_, err := q.db.Exec(ctx, dispatchJobMarkInProgress, arg.ID, arg.LastAttemptAt, arg.CreatedAt)
	return err
}

const dispatchJobPersist = `-- name: DispatchJobPersist :exec
UPDATE msg_dispatch_jobs
   SET status = $2,
       attempt_count = $3,
       scheduled_for = $4,
       completed_at = $5,
       duration_millis = $6,
       last_error = $7,
       updated_at = $8
 WHERE id = $1
   AND created_at = $9
`

type DispatchJobPersistParams struct {
	ID             string     `db:"id"`
	Status         string     `db:"status"`
	AttemptCount   int32      `db:"attempt_count"`
	ScheduledFor   *time.Time `db:"scheduled_for"`
	CompletedAt    *time.Time `db:"completed_at"`
	DurationMillis *int64     `db:"duration_millis"`
	LastError      *string    `db:"last_error"`
	UpdatedAt      time.Time  `db:"updated_at"`
	CreatedAt      time.Time  `db:"created_at"`
}

// Mutable-field update for human-initiated status overrides that go through
// the use-case envelope (cancel/complete/resend): scoped to the fields
// those operations ever change. payload/metadata/target_url/etc are
// write-once at ingest (DispatchJobInsert/InsertBatch) and never revisited
// by this path. created_at carries alongside id for partition pruning, like
// every other status-flip query in this file.
func (q *Queries) DispatchJobPersist(ctx context.Context, arg DispatchJobPersistParams) error {
	_, err := q.db.Exec(ctx, dispatchJobPersist,
		arg.ID,
		arg.Status,
		arg.AttemptCount,
		arg.ScheduledFor,
		arg.CompletedAt,
		arg.DurationMillis,
		arg.LastError,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}

const dispatchJobScheduleRetry = `-- name: DispatchJobScheduleRetry :exec
UPDATE msg_dispatch_jobs
   SET attempt_count = attempt_count + 1,
       scheduled_for = $2,
       last_error = $3,
       last_attempt_at = NOW(),
       status = 'PENDING',
       updated_at = NOW()
 WHERE id = $1
   AND created_at = $4
`

type DispatchJobScheduleRetryParams struct {
	ID           string     `db:"id"`
	ScheduledFor *time.Time `db:"scheduled_for"`
	LastError    *string    `db:"last_error"`
	CreatedAt    time.Time  `db:"created_at"`
}

// Bumps attempt_count + stamps scheduled_for so the next poll picks
// it up once due. Status stays PENDING.
func (q *Queries) DispatchJobScheduleRetry(ctx context.Context, arg DispatchJobScheduleRetryParams) error {
	_, err := q.db.Exec(ctx, dispatchJobScheduleRetry,
		arg.ID,
		arg.ScheduledFor,
		arg.LastError,
		arg.CreatedAt,
	)
	return err
}

const dispatchJobSettleAcked = `-- name: DispatchJobSettleAcked :many
UPDATE msg_dispatch_jobs
   SET status = 'PENDING',
       scheduled_for = NULL,
       last_error = $1::text,
       updated_at = NOW()
 WHERE id = ANY($2::text[])
   AND status IN ('QUEUED', 'PROCESSING')
RETURNING id
`

type DispatchJobSettleAckedParams struct {
	Reason string   `db:"reason"`
	Ids    []string `db:"ids"`
}

// The router→platform settled-message hook: resets the given ids to
// PENDING, recording the reason in last_error. Scoped to QUEUED/PROCESSING
// so a row a concurrent path already advanced (to a terminal status, or
// already back to PENDING) is left alone — idempotent, so a duplicate hook
// call is harmless. No created_at is available (the router only knows job
// ids), so this scans by id across partitions — the same accepted exception
// the pre-existing operator Requeue-turned-Resend path already relies on.
func (q *Queries) DispatchJobSettleAcked(ctx context.Context, arg DispatchJobSettleAckedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dispatchJobSettleAcked, arg.Reason, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchJobSweepStrandedSiblings = `-- name: DispatchJobSweepStrandedSiblings :many
WITH stranded AS (
    SELECT s.id, s.created_at
      FROM msg_dispatch_jobs s
      JOIN msg_dispatch_jobs h
        ON h.message_group = s.message_group
       -- Both terminal-failure statuses, matching dispatchjob.GroupHoldingStatusSQL
       -- exactly. 'ERROR' is the legacy value that predates the current status
       -- set; the poller still treats it as holding its group, so a sweep that
       -- recognised only 'FAILED' would leave siblings behind an ERROR head held
       -- at claim time but never reset here — stranded permanently, which is the
       -- failure this reaper exists to prevent.
       AND h.status IN ('FAILED', 'ERROR')
       AND (h.sequence, h.created_at, h.id) < (s.sequence, s.created_at, s.id)
     WHERE s.mode = 'BLOCK_ON_ERROR'
       AND s.message_group IS NOT NULL
       AND s.status IN ('QUEUED', 'PROCESSING')
       AND (s.status <> 'PROCESSING' OR s.updated_at < $2::timestamptz)
)
UPDATE msg_dispatch_jobs j
   SET status = 'PENDING',
       scheduled_for = NULL,
       last_error = $1::text,
       updated_at = NOW()
  FROM stranded st
 WHERE j.id = st.id AND j.created_at = st.created_at
RETURNING j.id
`

type DispatchJobSweepStrandedSiblingsParams struct {
	Reason     string    `db:"reason"`
	LiveBefore time.Time `db:"live_before"`
}

// The reaper backstop (reaper.go): resets to PENDING any QUEUED/PROCESSING
// job whose message group is headed by a terminally FAILED job under
// BLOCK_ON_ERROR — i.e. rows the settled-message hook should have caught
// but didn't (a dropped call, or a router crash between ACK and the hook).
// A PROCESSING row updated more recently than sqlc.arg('live_before') is
// presumed to be a genuine in-flight delivery and is left alone; QUEUED
// rows have no such window (see reaper.go for why). Idempotent — a row
// already reset by the hook no longer matches status IN (...) and is
// skipped on the next sweep.
func (q *Queries) DispatchJobSweepStrandedSiblings(ctx context.Context, arg DispatchJobSweepStrandedSiblingsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dispatchJobSweepStrandedSiblings, arg.Reason, arg.LiveBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
