// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatchpool.sql

package dbq

import (
	"context"
	"time"
)

const dispatchPoolDelete = `-- name: DispatchPoolDelete :exec
DELETE FROM msg_dispatch_pools WHERE id = $1
`

func (q *Queries) DispatchPoolDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, dispatchPoolDelete, id)
	return err
}

const dispatchPoolFindAll = `-- name: DispatchPoolFindAll :many
SELECT id, code, name, description, rate_limit, concurrency, client_id,
       client_identifier, status, created_at, updated_at
FROM msg_dispatch_pools
ORDER BY code
`

func (q *Queries) DispatchPoolFindAll(ctx context.Context) ([]MsgDispatchPool, error) {
	rows, err := q.db.Query(ctx, dispatchPoolFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgDispatchPool{}
	for rows.Next() {
		var i MsgDispatchPool
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.RateLimit,
			&i.Concurrency,
			&i.ClientID,
			&i.ClientIdentifier,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchPoolFindByCodeAnchor = `-- name: DispatchPoolFindByCodeAnchor :one
SELECT id, code, name, description, rate_limit, concurrency, client_id,
       client_identifier, status, created_at, updated_at
FROM msg_dispatch_pools
WHERE code = $1 AND client_id IS NULL
`

func (q *Queries) DispatchPoolFindByCodeAnchor(ctx context.Context, code string) (MsgDispatchPool, error) {
	row := q.db.QueryRow(ctx, dispatchPoolFindByCodeAnchor, code)
	var i MsgDispatchPool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.RateLimit,
		&i.Concurrency,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchPoolFindByCodeClient = `-- name: DispatchPoolFindByCodeClient :one
SELECT id, code, name, description, rate_limit, concurrency, client_id,
       client_identifier, status, created_at, updated_at
FROM msg_dispatch_pools
WHERE code = $1 AND client_id = $2
`

type DispatchPoolFindByCodeClientParams struct {
	Code     string
	ClientID *string
}

func (q *Queries) DispatchPoolFindByCodeClient(ctx context.Context, arg DispatchPoolFindByCodeClientParams) (MsgDispatchPool, error) {
	row := q.db.QueryRow(ctx, dispatchPoolFindByCodeClient, arg.Code, arg.ClientID)
	var i MsgDispatchPool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.RateLimit,
		&i.Concurrency,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchPoolFindByID = `-- name: DispatchPoolFindByID :one

SELECT id, code, name, description, rate_limit, concurrency, client_id,
       client_identifier, status, created_at, updated_at
FROM msg_dispatch_pools
WHERE id = $1
`

// Queries for msg_dispatch_pools.
func (q *Queries) DispatchPoolFindByID(ctx context.Context, id string) (MsgDispatchPool, error) {
	row := q.db.QueryRow(ctx, dispatchPoolFindByID, id)
	var i MsgDispatchPool
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.RateLimit,
		&i.Concurrency,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchPoolUpsert = `-- name: DispatchPoolUpsert :exec
INSERT INTO msg_dispatch_pools
    (id, code, name, description, rate_limit, concurrency, client_id,
     client_identifier, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    rate_limit = EXCLUDED.rate_limit,
    concurrency = EXCLUDED.concurrency,
    client_id = EXCLUDED.client_id,
    client_identifier = EXCLUDED.client_identifier,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
`

type DispatchPoolUpsertParams struct {
	ID               string
	Code             string
	Name             string
	Description      *string
	RateLimit        *int32
	Concurrency      int32
	ClientID         *string
	ClientIdentifier *string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) DispatchPoolUpsert(ctx context.Context, arg DispatchPoolUpsertParams) error {
	_, err := q.db.Exec(ctx, dispatchPoolUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.RateLimit,
		arg.Concurrency,
		arg.ClientID,
		arg.ClientIdentifier,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
