// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: function.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/flowcatalyst/flowcatalyst-go/internal/ids"
)

const functionAliasDelete = `-- name: FunctionAliasDelete :exec
DELETE FROM fng_aliases WHERE function_id = $1 AND name = $2
`

type FunctionAliasDeleteParams struct {
	FunctionID string `db:"function_id"`
	Name       string `db:"name"`
}

func (q *Queries) FunctionAliasDelete(ctx context.Context, arg FunctionAliasDeleteParams) error {
	_, err := q.db.Exec(ctx, functionAliasDelete, arg.FunctionID, arg.Name)
	return err
}

const functionAliasList = `-- name: FunctionAliasList :many
SELECT function_id, name, version_id, updated_at, updated_by
FROM fng_aliases
WHERE function_id = $1
ORDER BY name
`

func (q *Queries) FunctionAliasList(ctx context.Context, functionID string) ([]FngAlias, error) {
	rows, err := q.db.Query(ctx, functionAliasList, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FngAlias{}
	for rows.Next() {
		var i FngAlias
		if err := rows.Scan(
			&i.FunctionID,
			&i.Name,
			&i.VersionID,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const functionAliasUpsert = `-- name: FunctionAliasUpsert :exec
INSERT INTO fng_aliases (function_id, name, version_id, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (function_id, name) DO UPDATE SET
    version_id = EXCLUDED.version_id,
    updated_at = EXCLUDED.updated_at,
    updated_by = EXCLUDED.updated_by
`

type FunctionAliasUpsertParams struct {
	FunctionID string    `db:"function_id"`
	Name       string    `db:"name"`
	VersionID  string    `db:"version_id"`
	UpdatedAt  time.Time `db:"updated_at"`
	UpdatedBy  *string   `db:"updated_by"`
}

func (q *Queries) FunctionAliasUpsert(ctx context.Context, arg FunctionAliasUpsertParams) error {
	_, err := q.db.Exec(ctx, functionAliasUpsert,
		arg.FunctionID,
		arg.Name,
		arg.VersionID,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const functionDelete = `-- name: FunctionDelete :exec
DELETE FROM fng_functions WHERE id = $1
`

func (q *Queries) FunctionDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, functionDelete, id)
	return err
}

const functionFindByAddress = `-- name: FunctionFindByAddress :one
SELECT f.id, f.application_id, f.client_id, f.name, f.address, f.description, f.pool, f.warm, f.limits, f.created_by, f.created_at, f.updated_at, a.code AS application_code
FROM fng_functions f
LEFT JOIN app_applications a ON a.id = f.application_id
WHERE f.address = $1
`

type FunctionFindByAddressRow struct {
	FngFunction     FngFunction `db:"fng_function"`
	ApplicationCode *string     `db:"application_code"`
}

func (q *Queries) FunctionFindByAddress(ctx context.Context, address string) (FunctionFindByAddressRow, error) {
	row := q.db.QueryRow(ctx, functionFindByAddress, address)
	var i FunctionFindByAddressRow
	err := row.Scan(
		&i.FngFunction.ID,
		&i.FngFunction.ApplicationID,
		&i.FngFunction.ClientID,
		&i.FngFunction.Name,
		&i.FngFunction.Address,
		&i.FngFunction.Description,
		&i.FngFunction.Pool,
		&i.FngFunction.Warm,
		&i.FngFunction.Limits,
		&i.FngFunction.CreatedBy,
		&i.FngFunction.CreatedAt,
		&i.FngFunction.UpdatedAt,
		&i.ApplicationCode,
	)
	return i, err
}

const functionFindByID = `-- name: FunctionFindByID :one

SELECT f.id, f.application_id, f.client_id, f.name, f.address, f.description, f.pool, f.warm, f.limits, f.created_by, f.created_at, f.updated_at, a.code AS application_code
FROM fng_functions f
LEFT JOIN app_applications a ON a.id = f.application_id
WHERE f.id = $1
`

type FunctionFindByIDRow struct {
	FngFunction     FngFunction `db:"fng_function"`
	ApplicationCode *string     `db:"application_code"`
}

// Queries for fng_functions, fng_versions, fng_aliases, fng_settings,
// fng_runners, fng_pool_revisions.
func (q *Queries) FunctionFindByID(ctx context.Context, id string) (FunctionFindByIDRow, error) {
	row := q.db.QueryRow(ctx, functionFindByID, id)
	var i FunctionFindByIDRow
	err := row.Scan(
		&i.FngFunction.ID,
		&i.FngFunction.ApplicationID,
		&i.FngFunction.ClientID,
		&i.FngFunction.Name,
		&i.FngFunction.Address,
		&i.FngFunction.Description,
		&i.FngFunction.Pool,
		&i.FngFunction.Warm,
		&i.FngFunction.Limits,
		&i.FngFunction.CreatedBy,
		&i.FngFunction.CreatedAt,
		&i.FngFunction.UpdatedAt,
		&i.ApplicationCode,
	)
	return i, err
}

const functionPoolRevisionBump = `-- name: FunctionPoolRevisionBump :one
INSERT INTO fng_pool_revisions (pool, revision)
VALUES ($1, 1)
ON CONFLICT (pool) DO UPDATE SET revision = fng_pool_revisions.revision + 1
RETURNING revision
`

func (q *Queries) FunctionPoolRevisionBump(ctx context.Context, pool string) (int64, error) {
	row := q.db.QueryRow(ctx, functionPoolRevisionBump, pool)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const functionPoolRevisionGet = `-- name: FunctionPoolRevisionGet :one
SELECT revision FROM fng_pool_revisions WHERE pool = $1
`

func (q *Queries) FunctionPoolRevisionGet(ctx context.Context, pool string) (int64, error) {
	row := q.db.QueryRow(ctx, functionPoolRevisionGet, pool)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const functionRunnerUpsertHeartbeat = `-- name: FunctionRunnerUpsertHeartbeat :exec
INSERT INTO fng_runners (id, pool, heartbeat_at, report)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    pool = EXCLUDED.pool,
    heartbeat_at = EXCLUDED.heartbeat_at,
    report = EXCLUDED.report
`

type FunctionRunnerUpsertHeartbeatParams struct {
	ID          string          `db:"id"`
	Pool        string          `db:"pool"`
	HeartbeatAt time.Time       `db:"heartbeat_at"`
	Report      json.RawMessage `db:"report"`
}

func (q *Queries) FunctionRunnerUpsertHeartbeat(ctx context.Context, arg FunctionRunnerUpsertHeartbeatParams) error {
	_, err := q.db.Exec(ctx, functionRunnerUpsertHeartbeat,
		arg.ID,
		arg.Pool,
		arg.HeartbeatAt,
		arg.Report,
	)
	return err
}

const functionSettingDelete = `-- name: FunctionSettingDelete :exec
DELETE FROM fng_settings WHERE function_id = $1 AND kind = $2 AND key = $3
`

type FunctionSettingDeleteParams struct {
	FunctionID string `db:"function_id"`
	Kind       string `db:"kind"`
	Key        string `db:"key"`
}

func (q *Queries) FunctionSettingDelete(ctx context.Context, arg FunctionSettingDeleteParams) error {
	_, err := q.db.Exec(ctx, functionSettingDelete, arg.FunctionID, arg.Kind, arg.Key)
	return err
}

const functionSettingList = `-- name: FunctionSettingList :many
SELECT function_id, kind, key, value, updated_at
FROM fng_settings
WHERE function_id = $1
ORDER BY kind, key
`

func (q *Queries) FunctionSettingList(ctx context.Context, functionID string) ([]FngSetting, error) {
	rows, err := q.db.Query(ctx, functionSettingList, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FngSetting{}
	for rows.Next() {
		var i FngSetting
		if err := rows.Scan(
			&i.FunctionID,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const functionSettingUpsert = `-- name: FunctionSettingUpsert :exec
INSERT INTO fng_settings (function_id, kind, key, value, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (function_id, kind, key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
`

type FunctionSettingUpsertParams struct {
	FunctionID string    `db:"function_id"`
	Kind       string    `db:"kind"`
	Key        string    `db:"key"`
	Value      string    `db:"value"`
	UpdatedAt  time.Time `db:"updated_at"`
}

func (q *Queries) FunctionSettingUpsert(ctx context.Context, arg FunctionSettingUpsertParams) error {
	_, err := q.db.Exec(ctx, functionSettingUpsert,
		arg.FunctionID,
		arg.Kind,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const functionUpsert = `-- name: FunctionUpsert :exec
INSERT INTO fng_functions
    (id, application_id, client_id, name, address, description, pool, warm,
     limits, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    description = EXCLUDED.description,
    pool = EXCLUDED.pool,
    warm = EXCLUDED.warm,
    limits = EXCLUDED.limits,
    updated_at = EXCLUDED.updated_at
`

type FunctionUpsertParams struct {
	ID            string            `db:"id"`
	ApplicationID ids.ApplicationID `db:"application_id"`
	ClientID      *ids.ClientID     `db:"client_id"`
	Name          string            `db:"name"`
	Address       string            `db:"address"`
	Description   *string           `db:"description"`
	Pool          *string           `db:"pool"`
	Warm          bool              `db:"warm"`
	Limits        json.RawMessage   `db:"limits"`
	CreatedBy     *string           `db:"created_by"`
	CreatedAt     time.Time         `db:"created_at"`
	UpdatedAt     time.Time         `db:"updated_at"`
}

func (q *Queries) FunctionUpsert(ctx context.Context, arg FunctionUpsertParams) error {
	_, err := q.db.Exec(ctx, functionUpsert,
		arg.ID,
		arg.ApplicationID,
		arg.ClientID,
		arg.Name,
		arg.Address,
		arg.Description,
		arg.Pool,
		arg.Warm,
		arg.Limits,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const functionVersionGetByDigest = `-- name: FunctionVersionGetByDigest :one
SELECT id, function_id, number, digest, size_bytes, abi, describe, status,
       failure, ready_at, published_by, created_at
FROM fng_versions
WHERE function_id = $1 AND digest = $2
`

type FunctionVersionGetByDigestParams struct {
	FunctionID string `db:"function_id"`
	Digest     string `db:"digest"`
}

type FunctionVersionGetByDigestRow struct {
	ID          string          `db:"id"`
	FunctionID  string          `db:"function_id"`
	Number      int32           `db:"number"`
	Digest      string          `db:"digest"`
	SizeBytes   int64           `db:"size_bytes"`
	Abi         int32           `db:"abi"`
	Describe    json.RawMessage `db:"describe"`
	Status      string          `db:"status"`
	Failure     json.RawMessage `db:"failure"`
	ReadyAt     *time.Time      `db:"ready_at"`
	PublishedBy *string         `db:"published_by"`
	CreatedAt   time.Time       `db:"created_at"`
}

func (q *Queries) FunctionVersionGetByDigest(ctx context.Context, arg FunctionVersionGetByDigestParams) (FunctionVersionGetByDigestRow, error) {
	row := q.db.QueryRow(ctx, functionVersionGetByDigest, arg.FunctionID, arg.Digest)
	var i FunctionVersionGetByDigestRow
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.Number,
		&i.Digest,
		&i.SizeBytes,
		&i.Abi,
		&i.Describe,
		&i.Status,
		&i.Failure,
		&i.ReadyAt,
		&i.PublishedBy,
		&i.CreatedAt,
	)
	return i, err
}

const functionVersionGetByNumber = `-- name: FunctionVersionGetByNumber :one
SELECT id, function_id, number, digest, size_bytes, abi, describe, status,
       failure, ready_at, published_by, created_at
FROM fng_versions
WHERE function_id = $1 AND number = $2
`

type FunctionVersionGetByNumberParams struct {
	FunctionID string `db:"function_id"`
	Number     int32  `db:"number"`
}

type FunctionVersionGetByNumberRow struct {
	ID          string          `db:"id"`
	FunctionID  string          `db:"function_id"`
	Number      int32           `db:"number"`
	Digest      string          `db:"digest"`
	SizeBytes   int64           `db:"size_bytes"`
	Abi         int32           `db:"abi"`
	Describe    json.RawMessage `db:"describe"`
	Status      string          `db:"status"`
	Failure     json.RawMessage `db:"failure"`
	ReadyAt     *time.Time      `db:"ready_at"`
	PublishedBy *string         `db:"published_by"`
	CreatedAt   time.Time       `db:"created_at"`
}

func (q *Queries) FunctionVersionGetByNumber(ctx context.Context, arg FunctionVersionGetByNumberParams) (FunctionVersionGetByNumberRow, error) {
	row := q.db.QueryRow(ctx, functionVersionGetByNumber, arg.FunctionID, arg.Number)
	var i FunctionVersionGetByNumberRow
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.Number,
		&i.Digest,
		&i.SizeBytes,
		&i.Abi,
		&i.Describe,
		&i.Status,
		&i.Failure,
		&i.ReadyAt,
		&i.PublishedBy,
		&i.CreatedAt,
	)
	return i, err
}

const functionVersionInsert = `-- name: FunctionVersionInsert :exec
INSERT INTO fng_versions
    (id, function_id, number, digest, size_bytes, abi, describe, status,
     failure, ready_at, published_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type FunctionVersionInsertParams struct {
	ID          string          `db:"id"`
	FunctionID  string          `db:"function_id"`
	Number      int32           `db:"number"`
	Digest      string          `db:"digest"`
	SizeBytes   int64           `db:"size_bytes"`
	Abi         int32           `db:"abi"`
	Describe    json.RawMessage `db:"describe"`
	Status      string          `db:"status"`
	Failure     json.RawMessage `db:"failure"`
	ReadyAt     *time.Time      `db:"ready_at"`
	PublishedBy *string         `db:"published_by"`
	CreatedAt   time.Time       `db:"created_at"`
}

func (q *Queries) FunctionVersionInsert(ctx context.Context, arg FunctionVersionInsertParams) error {
	_, err := q.db.Exec(ctx, functionVersionInsert,
		arg.ID,
		arg.FunctionID,
		arg.Number,
		arg.Digest,
		arg.SizeBytes,
		arg.Abi,
		arg.Describe,
		arg.Status,
		arg.Failure,
		arg.ReadyAt,
		arg.PublishedBy,
		arg.CreatedAt,
	)
	return err
}

const functionVersionListByFunction = `-- name: FunctionVersionListByFunction :many
SELECT id, function_id, number, digest, size_bytes, abi, describe, status,
       failure, ready_at, published_by, created_at
FROM fng_versions
WHERE function_id = $1
ORDER BY number DESC
`

type FunctionVersionListByFunctionRow struct {
	ID          string          `db:"id"`
	FunctionID  string          `db:"function_id"`
	Number      int32           `db:"number"`
	Digest      string          `db:"digest"`
	SizeBytes   int64           `db:"size_bytes"`
	Abi         int32           `db:"abi"`
	Describe    json.RawMessage `db:"describe"`
	Status      string          `db:"status"`
	Failure     json.RawMessage `db:"failure"`
	ReadyAt     *time.Time      `db:"ready_at"`
	PublishedBy *string         `db:"published_by"`
	CreatedAt   time.Time       `db:"created_at"`
}

func (q *Queries) FunctionVersionListByFunction(ctx context.Context, functionID string) ([]FunctionVersionListByFunctionRow, error) {
	rows, err := q.db.Query(ctx, functionVersionListByFunction, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FunctionVersionListByFunctionRow{}
	for rows.Next() {
		var i FunctionVersionListByFunctionRow
		if err := rows.Scan(
			&i.ID,
			&i.FunctionID,
			&i.Number,
			&i.Digest,
			&i.SizeBytes,
			&i.Abi,
			&i.Describe,
			&i.Status,
			&i.Failure,
			&i.ReadyAt,
			&i.PublishedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const functionVersionSetFailure = `-- name: FunctionVersionSetFailure :exec
UPDATE fng_versions SET status = 'FAILED', failure = $2 WHERE id = $1
`

type FunctionVersionSetFailureParams struct {
	ID      string          `db:"id"`
	Failure json.RawMessage `db:"failure"`
}

func (q *Queries) FunctionVersionSetFailure(ctx context.Context, arg FunctionVersionSetFailureParams) error {
	_, err := q.db.Exec(ctx, functionVersionSetFailure, arg.ID, arg.Failure)
	return err
}

const functionVersionSetReady = `-- name: FunctionVersionSetReady :exec
UPDATE fng_versions SET status = 'READY', ready_at = $2 WHERE id = $1
`

type FunctionVersionSetReadyParams struct {
	ID      string     `db:"id"`
	ReadyAt *time.Time `db:"ready_at"`
}

func (q *Queries) FunctionVersionSetReady(ctx context.Context, arg FunctionVersionSetReadyParams) error {
	_, err := q.db.Exec(ctx, functionVersionSetReady, arg.ID, arg.ReadyAt)
	return err
}

const functionVersionSetStatus = `-- name: FunctionVersionSetStatus :exec
UPDATE fng_versions SET status = $2 WHERE id = $1
`

type FunctionVersionSetStatusParams struct {
	ID     string `db:"id"`
	Status string `db:"status"`
}

func (q *Queries) FunctionVersionSetStatus(ctx context.Context, arg FunctionVersionSetStatusParams) error {
	_, err := q.db.Exec(ctx, functionVersionSetStatus, arg.ID, arg.Status)
	return err
}
