// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identityprovider.sql

package dbq

import (
	"context"
	"time"
)

const identityProviderDelete = `-- name: IdentityProviderDelete :exec
DELETE FROM oauth_identity_providers WHERE id = $1
`

func (q *Queries) IdentityProviderDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, identityProviderDelete, id)
	return err
}

const identityProviderDomainInsert = `-- name: IdentityProviderDomainInsert :exec
INSERT INTO oauth_identity_provider_allowed_domains
    (identity_provider_id, email_domain)
VALUES ($1, $2)
`

type IdentityProviderDomainInsertParams struct {
	IdentityProviderID string
	EmailDomain        string
}

func (q *Queries) IdentityProviderDomainInsert(ctx context.Context, arg IdentityProviderDomainInsertParams) error {
	_, err := q.db.Exec(ctx, identityProviderDomainInsert, arg.IdentityProviderID, arg.EmailDomain)
	return err
}

const identityProviderDomainsClear = `-- name: IdentityProviderDomainsClear :exec
DELETE FROM oauth_identity_provider_allowed_domains WHERE identity_provider_id = $1
`

func (q *Queries) IdentityProviderDomainsClear(ctx context.Context, identityProviderID string) error {
	_, err := q.db.Exec(ctx, identityProviderDomainsClear, identityProviderID)
	return err
}

const identityProviderDomainsForIDPs = `-- name: IdentityProviderDomainsForIDPs :many
SELECT identity_provider_id, email_domain
FROM oauth_identity_provider_allowed_domains
WHERE identity_provider_id = ANY($1::text[])
ORDER BY identity_provider_id, email_domain
`

type IdentityProviderDomainsForIDPsRow struct {
	IdentityProviderID string
	EmailDomain        string
}

func (q *Queries) IdentityProviderDomainsForIDPs(ctx context.Context, idpIds []string) ([]IdentityProviderDomainsForIDPsRow, error) {
	rows, err := q.db.Query(ctx, identityProviderDomainsForIDPs, idpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProviderDomainsForIDPsRow{}
	for rows.Next() {
		var i IdentityProviderDomainsForIDPsRow
		if err := rows.Scan(&i.IdentityProviderID, &i.EmailDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityProviderFindAll = `-- name: IdentityProviderFindAll :many
SELECT id, code, name, type, oidc_issuer_url, oidc_client_id,
       oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
       created_at, updated_at
FROM oauth_identity_providers
ORDER BY code
`

func (q *Queries) IdentityProviderFindAll(ctx context.Context) ([]OauthIdentityProvider, error) {
	rows, err := q.db.Query(ctx, identityProviderFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdentityProvider{}
	for rows.Next() {
		var i OauthIdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.OidcIssuerUrl,
			&i.OidcClientID,
			&i.OidcClientSecretRef,
			&i.OidcMultiTenant,
			&i.OidcIssuerPattern,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityProviderFindByCode = `-- name: IdentityProviderFindByCode :one
SELECT id, code, name, type, oidc_issuer_url, oidc_client_id,
       oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
       created_at, updated_at
FROM oauth_identity_providers
WHERE code = $1
`

func (q *Queries) IdentityProviderFindByCode(ctx context.Context, code string) (OauthIdentityProvider, error) {
	row := q.db.QueryRow(ctx, identityProviderFindByCode, code)
	var i OauthIdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcClientSecretRef,
		&i.OidcMultiTenant,
		&i.OidcIssuerPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityProviderFindByID = `-- name: IdentityProviderFindByID :one

SELECT id, code, name, type, oidc_issuer_url, oidc_client_id,
       oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
       created_at, updated_at
FROM oauth_identity_providers
WHERE id = $1
`

// Queries for oauth_identity_providers + oauth_identity_provider_allowed_domains.
// Email domains are stored in the junction table (one row per allowed domain),
// not as a column on the parent — the previous Go port incorrectly treated
// this as a single JSONB-style column.
func (q *Queries) IdentityProviderFindByID(ctx context.Context, id string) (OauthIdentityProvider, error) {
	row := q.db.QueryRow(ctx, identityProviderFindByID, id)
	var i OauthIdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcClientSecretRef,
		&i.OidcMultiTenant,
		&i.OidcIssuerPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityProviderUpsert = `-- name: IdentityProviderUpsert :exec
INSERT INTO oauth_identity_providers
    (id, code, name, type, oidc_issuer_url, oidc_client_id,
     oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
     created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    oidc_issuer_url = EXCLUDED.oidc_issuer_url,
    oidc_client_id = EXCLUDED.oidc_client_id,
    oidc_client_secret_ref = EXCLUDED.oidc_client_secret_ref,
    oidc_multi_tenant = EXCLUDED.oidc_multi_tenant,
    oidc_issuer_pattern = EXCLUDED.oidc_issuer_pattern,
    updated_at = EXCLUDED.updated_at
`

type IdentityProviderUpsertParams struct {
	ID                  string
	Code                string
	Name                string
	Type                string
	OidcIssuerUrl       *string
	OidcClientID        *string
	OidcClientSecretRef *string
	OidcMultiTenant     bool
	OidcIssuerPattern   *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) IdentityProviderUpsert(ctx context.Context, arg IdentityProviderUpsertParams) error {
	_, err := q.db.Exec(ctx, identityProviderUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.OidcIssuerUrl,
		arg.OidcClientID,
		arg.OidcClientSecretRef,
		arg.OidcMultiTenant,
		arg.OidcIssuerPattern,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
