// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identityprovider.sql

package dbq

import (
	"context"
	"time"
)

const identityProviderAllowedRoleInsert = `-- name: IdentityProviderAllowedRoleInsert :exec
INSERT INTO oauth_identity_provider_allowed_roles
    (identity_provider_id, role_id)
VALUES ($1, $2)
`

type IdentityProviderAllowedRoleInsertParams struct {
	IdentityProviderID string `db:"identity_provider_id"`
	RoleID             string `db:"role_id"`
}

func (q *Queries) IdentityProviderAllowedRoleInsert(ctx context.Context, arg IdentityProviderAllowedRoleInsertParams) error {
	_, err := q.db.Exec(ctx, identityProviderAllowedRoleInsert, arg.IdentityProviderID, arg.RoleID)
	return err
}

const identityProviderAllowedRolesClear = `-- name: IdentityProviderAllowedRolesClear :exec
DELETE FROM oauth_identity_provider_allowed_roles WHERE identity_provider_id = $1
`

func (q *Queries) IdentityProviderAllowedRolesClear(ctx context.Context, identityProviderID string) error {
	_, err := q.db.Exec(ctx, identityProviderAllowedRolesClear, identityProviderID)
	return err
}

const identityProviderAllowedRolesForIDPs = `-- name: IdentityProviderAllowedRolesForIDPs :many
SELECT identity_provider_id, role_id
FROM oauth_identity_provider_allowed_roles
WHERE identity_provider_id = ANY($1::text[])
ORDER BY identity_provider_id, role_id
`

type IdentityProviderAllowedRolesForIDPsRow struct {
	IdentityProviderID string `db:"identity_provider_id"`
	RoleID             string `db:"role_id"`
}

func (q *Queries) IdentityProviderAllowedRolesForIDPs(ctx context.Context, idpIds []string) ([]IdentityProviderAllowedRolesForIDPsRow, error) {
	rows, err := q.db.Query(ctx, identityProviderAllowedRolesForIDPs, idpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProviderAllowedRolesForIDPsRow{}
	for rows.Next() {
		var i IdentityProviderAllowedRolesForIDPsRow
		if err := rows.Scan(&i.IdentityProviderID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityProviderDelete = `-- name: IdentityProviderDelete :exec
DELETE FROM oauth_identity_providers WHERE id = $1
`

func (q *Queries) IdentityProviderDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, identityProviderDelete, id)
	return err
}

const identityProviderDomainsClear = `-- name: IdentityProviderDomainsClear :exec
DELETE FROM oauth_identity_provider_allowed_domains WHERE identity_provider_id = $1
`

func (q *Queries) IdentityProviderDomainsClear(ctx context.Context, identityProviderID string) error {
	_, err := q.db.Exec(ctx, identityProviderDomainsClear, identityProviderID)
	return err
}

const identityProviderFindAll = `-- name: IdentityProviderFindAll :many
SELECT id, code, name, type, oidc_issuer_url, oidc_client_id,
       oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
       created_at, updated_at, sync_roles_from_idp, portal_client_id
FROM oauth_identity_providers
ORDER BY code
`

func (q *Queries) IdentityProviderFindAll(ctx context.Context) ([]OauthIdentityProvider, error) {
	rows, err := q.db.Query(ctx, identityProviderFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdentityProvider{}
	for rows.Next() {
		var i OauthIdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.OidcIssuerUrl,
			&i.OidcClientID,
			&i.OidcClientSecretRef,
			&i.OidcMultiTenant,
			&i.OidcIssuerPattern,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncRolesFromIdp,
			&i.PortalClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityProviderFindByCode = `-- name: IdentityProviderFindByCode :one
SELECT id, code, name, type, oidc_issuer_url, oidc_client_id,
       oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
       created_at, updated_at, sync_roles_from_idp, portal_client_id
FROM oauth_identity_providers
WHERE code = $1
`

func (q *Queries) IdentityProviderFindByCode(ctx context.Context, code string) (OauthIdentityProvider, error) {
	row := q.db.QueryRow(ctx, identityProviderFindByCode, code)
	var i OauthIdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcClientSecretRef,
		&i.OidcMultiTenant,
		&i.OidcIssuerPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncRolesFromIdp,
		&i.PortalClientID,
	)
	return i, err
}

const identityProviderFindByID = `-- name: IdentityProviderFindByID :one

SELECT id, code, name, type, oidc_issuer_url, oidc_client_id,
       oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
       created_at, updated_at, sync_roles_from_idp, portal_client_id
FROM oauth_identity_providers
WHERE id = $1
`

// Queries for oauth_identity_providers + oauth_identity_provider_allowed_roles.
// The allowed-roles junction (one row per platform role the IDP may confer via
// role sync) lives here since migration 040. Allowed email domains are NOT
// stored on the provider — they are derived from tnt_email_domain_mappings
// (see IdentityProviderMappedDomainsForIDPs), which is the single source of
// truth for domain → IDP routing. The legacy
// oauth_identity_provider_allowed_domains junction is dead.
func (q *Queries) IdentityProviderFindByID(ctx context.Context, id string) (OauthIdentityProvider, error) {
	row := q.db.QueryRow(ctx, identityProviderFindByID, id)
	var i OauthIdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.OidcIssuerUrl,
		&i.OidcClientID,
		&i.OidcClientSecretRef,
		&i.OidcMultiTenant,
		&i.OidcIssuerPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncRolesFromIdp,
		&i.PortalClientID,
	)
	return i, err
}

const identityProviderMappedDomainsForIDPs = `-- name: IdentityProviderMappedDomainsForIDPs :many
SELECT identity_provider_id, email_domain
FROM tnt_email_domain_mappings
WHERE identity_provider_id = ANY($1::text[])
ORDER BY identity_provider_id, email_domain
`

type IdentityProviderMappedDomainsForIDPsRow struct {
	IdentityProviderID string `db:"identity_provider_id"`
	EmailDomain        string `db:"email_domain"`
}

func (q *Queries) IdentityProviderMappedDomainsForIDPs(ctx context.Context, idpIds []string) ([]IdentityProviderMappedDomainsForIDPsRow, error) {
	rows, err := q.db.Query(ctx, identityProviderMappedDomainsForIDPs, idpIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProviderMappedDomainsForIDPsRow{}
	for rows.Next() {
		var i IdentityProviderMappedDomainsForIDPsRow
		if err := rows.Scan(&i.IdentityProviderID, &i.EmailDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityProviderUpsert = `-- name: IdentityProviderUpsert :exec
INSERT INTO oauth_identity_providers
    (id, code, name, type, oidc_issuer_url, oidc_client_id,
     oidc_client_secret_ref, oidc_multi_tenant, oidc_issuer_pattern,
     sync_roles_from_idp, created_at, updated_at, portal_client_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    oidc_issuer_url = EXCLUDED.oidc_issuer_url,
    oidc_client_id = EXCLUDED.oidc_client_id,
    oidc_client_secret_ref = EXCLUDED.oidc_client_secret_ref,
    oidc_multi_tenant = EXCLUDED.oidc_multi_tenant,
    oidc_issuer_pattern = EXCLUDED.oidc_issuer_pattern,
    sync_roles_from_idp = EXCLUDED.sync_roles_from_idp,
    updated_at = EXCLUDED.updated_at,
    portal_client_id = EXCLUDED.portal_client_id
`

type IdentityProviderUpsertParams struct {
	ID                  string    `db:"id"`
	Code                string    `db:"code"`
	Name                string    `db:"name"`
	Type                string    `db:"type"`
	OidcIssuerUrl       *string   `db:"oidc_issuer_url"`
	OidcClientID        *string   `db:"oidc_client_id"`
	OidcClientSecretRef *string   `db:"oidc_client_secret_ref"`
	OidcMultiTenant     bool      `db:"oidc_multi_tenant"`
	OidcIssuerPattern   *string   `db:"oidc_issuer_pattern"`
	SyncRolesFromIdp    bool      `db:"sync_roles_from_idp"`
	CreatedAt           time.Time `db:"created_at"`
	UpdatedAt           time.Time `db:"updated_at"`
	PortalClientID      *string   `db:"portal_client_id"`
}

func (q *Queries) IdentityProviderUpsert(ctx context.Context, arg IdentityProviderUpsertParams) error {
	_, err := q.db.Exec(ctx, identityProviderUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.OidcIssuerUrl,
		arg.OidcClientID,
		arg.OidcClientSecretRef,
		arg.OidcMultiTenant,
		arg.OidcIssuerPattern,
		arg.SyncRolesFromIdp,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PortalClientID,
	)
	return err
}
