// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payload.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const oAuthPayloadDelete = `-- name: OAuthPayloadDelete :exec
DELETE FROM oauth_oidc_payloads WHERE id = $1
`

func (q *Queries) OAuthPayloadDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, oAuthPayloadDelete, id)
	return err
}

const oAuthPayloadDeleteByGrant = `-- name: OAuthPayloadDeleteByGrant :exec
DELETE FROM oauth_oidc_payloads WHERE grant_id = $1
`

func (q *Queries) OAuthPayloadDeleteByGrant(ctx context.Context, grantID *string) error {
	_, err := q.db.Exec(ctx, oAuthPayloadDeleteByGrant, grantID)
	return err
}

const oAuthPayloadFindByID = `-- name: OAuthPayloadFindByID :one
SELECT id, type, payload, grant_id, user_code, uid, expires_at, consumed_at, created_at
FROM oauth_oidc_payloads
WHERE id = $1 AND type = $2
`

type OAuthPayloadFindByIDParams struct {
	ID   string
	Type string
}

func (q *Queries) OAuthPayloadFindByID(ctx context.Context, arg OAuthPayloadFindByIDParams) (OauthOidcPayload, error) {
	row := q.db.QueryRow(ctx, oAuthPayloadFindByID, arg.ID, arg.Type)
	var i OauthOidcPayload
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.GrantID,
		&i.UserCode,
		&i.Uid,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const oAuthPayloadInsert = `-- name: OAuthPayloadInsert :exec

INSERT INTO oauth_oidc_payloads
    (id, type, payload, grant_id, user_code, uid, expires_at, consumed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type OAuthPayloadInsertParams struct {
	ID         string
	Type       string
	Payload    json.RawMessage
	GrantID    *string
	UserCode   *string
	Uid        *string
	ExpiresAt  *time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

// Queries for oauth_oidc_payloads — fosite-backed OIDC artifact store
// (access/refresh tokens, authorization codes, PKCE sessions, etc.).
// Webauthn ceremonies use this same table; their queries live in
// webauthn_ceremony.sql so each subsystem owns its own slice.
func (q *Queries) OAuthPayloadInsert(ctx context.Context, arg OAuthPayloadInsertParams) error {
	_, err := q.db.Exec(ctx, oAuthPayloadInsert,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.GrantID,
		arg.UserCode,
		arg.Uid,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.CreatedAt,
	)
	return err
}

const oAuthPayloadMarkConsumed = `-- name: OAuthPayloadMarkConsumed :exec
UPDATE oauth_oidc_payloads SET consumed_at = NOW() WHERE id = $1
`

func (q *Queries) OAuthPayloadMarkConsumed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, oAuthPayloadMarkConsumed, id)
	return err
}

const oAuthPayloadPurgeExpired = `-- name: OAuthPayloadPurgeExpired :execrows
DELETE FROM oauth_oidc_payloads
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) OAuthPayloadPurgeExpired(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, oAuthPayloadPurgeExpired)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
