// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platformconfig.sql

package dbq

import (
	"context"
	"time"
)

const platformConfigAccessDelete = `-- name: PlatformConfigAccessDelete :exec
DELETE FROM app_platform_config_access WHERE id = $1
`

func (q *Queries) PlatformConfigAccessDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, platformConfigAccessDelete, id)
	return err
}

const platformConfigAccessFindByApplication = `-- name: PlatformConfigAccessFindByApplication :many
SELECT id, application_code, role_code, can_read, can_write, created_at
FROM app_platform_config_access
WHERE application_code = $1
ORDER BY role_code
`

func (q *Queries) PlatformConfigAccessFindByApplication(ctx context.Context, applicationCode string) ([]AppPlatformConfigAccess, error) {
	rows, err := q.db.Query(ctx, platformConfigAccessFindByApplication, applicationCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlatformConfigAccess{}
	for rows.Next() {
		var i AppPlatformConfigAccess
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationCode,
			&i.RoleCode,
			&i.CanRead,
			&i.CanWrite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformConfigAccessFindByID = `-- name: PlatformConfigAccessFindByID :one
SELECT id, application_code, role_code, can_read, can_write, created_at
FROM app_platform_config_access
WHERE id = $1
`

func (q *Queries) PlatformConfigAccessFindByID(ctx context.Context, id string) (AppPlatformConfigAccess, error) {
	row := q.db.QueryRow(ctx, platformConfigAccessFindByID, id)
	var i AppPlatformConfigAccess
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.RoleCode,
		&i.CanRead,
		&i.CanWrite,
		&i.CreatedAt,
	)
	return i, err
}

const platformConfigAccessFindByRole = `-- name: PlatformConfigAccessFindByRole :one
SELECT id, application_code, role_code, can_read, can_write, created_at
FROM app_platform_config_access
WHERE application_code = $1 AND role_code = $2
`

type PlatformConfigAccessFindByRoleParams struct {
	ApplicationCode string `db:"application_code"`
	RoleCode        string `db:"role_code"`
}

func (q *Queries) PlatformConfigAccessFindByRole(ctx context.Context, arg PlatformConfigAccessFindByRoleParams) (AppPlatformConfigAccess, error) {
	row := q.db.QueryRow(ctx, platformConfigAccessFindByRole, arg.ApplicationCode, arg.RoleCode)
	var i AppPlatformConfigAccess
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.RoleCode,
		&i.CanRead,
		&i.CanWrite,
		&i.CreatedAt,
	)
	return i, err
}

const platformConfigAccessHasReadByRoles = `-- name: PlatformConfigAccessHasReadByRoles :one
SELECT EXISTS(
    SELECT 1 FROM app_platform_config_access
    WHERE application_code = $1
      AND role_code = ANY($2::text[])
      AND can_read = true
)
`

type PlatformConfigAccessHasReadByRolesParams struct {
	ApplicationCode string   `db:"application_code"`
	RoleCodes       []string `db:"role_codes"`
}

func (q *Queries) PlatformConfigAccessHasReadByRoles(ctx context.Context, arg PlatformConfigAccessHasReadByRolesParams) (bool, error) {
	row := q.db.QueryRow(ctx, platformConfigAccessHasReadByRoles, arg.ApplicationCode, arg.RoleCodes)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const platformConfigAccessHasWriteByRoles = `-- name: PlatformConfigAccessHasWriteByRoles :one
SELECT EXISTS(
    SELECT 1 FROM app_platform_config_access
    WHERE application_code = $1
      AND role_code = ANY($2::text[])
      AND can_write = true
)
`

type PlatformConfigAccessHasWriteByRolesParams struct {
	ApplicationCode string   `db:"application_code"`
	RoleCodes       []string `db:"role_codes"`
}

func (q *Queries) PlatformConfigAccessHasWriteByRoles(ctx context.Context, arg PlatformConfigAccessHasWriteByRolesParams) (bool, error) {
	row := q.db.QueryRow(ctx, platformConfigAccessHasWriteByRoles, arg.ApplicationCode, arg.RoleCodes)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const platformConfigAccessUpsert = `-- name: PlatformConfigAccessUpsert :exec
INSERT INTO app_platform_config_access
    (id, application_code, role_code, can_read, can_write, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    can_read = EXCLUDED.can_read,
    can_write = EXCLUDED.can_write
`

type PlatformConfigAccessUpsertParams struct {
	ID              string    `db:"id"`
	ApplicationCode string    `db:"application_code"`
	RoleCode        string    `db:"role_code"`
	CanRead         bool      `db:"can_read"`
	CanWrite        bool      `db:"can_write"`
	CreatedAt       time.Time `db:"created_at"`
}

func (q *Queries) PlatformConfigAccessUpsert(ctx context.Context, arg PlatformConfigAccessUpsertParams) error {
	_, err := q.db.Exec(ctx, platformConfigAccessUpsert,
		arg.ID,
		arg.ApplicationCode,
		arg.RoleCode,
		arg.CanRead,
		arg.CanWrite,
		arg.CreatedAt,
	)
	return err
}

const platformConfigDelete = `-- name: PlatformConfigDelete :exec
DELETE FROM app_platform_configs WHERE id = $1
`

func (q *Queries) PlatformConfigDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, platformConfigDelete, id)
	return err
}

const platformConfigFindByApplication = `-- name: PlatformConfigFindByApplication :many
SELECT id, application_code, section, property, scope, client_id,
       value_type, value, description, created_at, updated_at
FROM app_platform_configs
WHERE application_code = $1
ORDER BY section, property
`

func (q *Queries) PlatformConfigFindByApplication(ctx context.Context, applicationCode string) ([]AppPlatformConfig, error) {
	rows, err := q.db.Query(ctx, platformConfigFindByApplication, applicationCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPlatformConfig{}
	for rows.Next() {
		var i AppPlatformConfig
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationCode,
			&i.Section,
			&i.Property,
			&i.Scope,
			&i.ClientID,
			&i.ValueType,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformConfigFindByCoordinateAnchor = `-- name: PlatformConfigFindByCoordinateAnchor :one
SELECT id, application_code, section, property, scope, client_id,
       value_type, value, description, created_at, updated_at
FROM app_platform_configs
WHERE application_code = $1 AND section = $2 AND property = $3
  AND scope = $4 AND client_id IS NULL
`

type PlatformConfigFindByCoordinateAnchorParams struct {
	ApplicationCode string `db:"application_code"`
	Section         string `db:"section"`
	Property        string `db:"property"`
	Scope           string `db:"scope"`
}

func (q *Queries) PlatformConfigFindByCoordinateAnchor(ctx context.Context, arg PlatformConfigFindByCoordinateAnchorParams) (AppPlatformConfig, error) {
	row := q.db.QueryRow(ctx, platformConfigFindByCoordinateAnchor,
		arg.ApplicationCode,
		arg.Section,
		arg.Property,
		arg.Scope,
	)
	var i AppPlatformConfig
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Section,
		&i.Property,
		&i.Scope,
		&i.ClientID,
		&i.ValueType,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const platformConfigFindByCoordinateClient = `-- name: PlatformConfigFindByCoordinateClient :one
SELECT id, application_code, section, property, scope, client_id,
       value_type, value, description, created_at, updated_at
FROM app_platform_configs
WHERE application_code = $1 AND section = $2 AND property = $3
  AND scope = $4 AND client_id = $5
`

type PlatformConfigFindByCoordinateClientParams struct {
	ApplicationCode string  `db:"application_code"`
	Section         string  `db:"section"`
	Property        string  `db:"property"`
	Scope           string  `db:"scope"`
	ClientID        *string `db:"client_id"`
}

func (q *Queries) PlatformConfigFindByCoordinateClient(ctx context.Context, arg PlatformConfigFindByCoordinateClientParams) (AppPlatformConfig, error) {
	row := q.db.QueryRow(ctx, platformConfigFindByCoordinateClient,
		arg.ApplicationCode,
		arg.Section,
		arg.Property,
		arg.Scope,
		arg.ClientID,
	)
	var i AppPlatformConfig
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Section,
		&i.Property,
		&i.Scope,
		&i.ClientID,
		&i.ValueType,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const platformConfigFindByID = `-- name: PlatformConfigFindByID :one

SELECT id, application_code, section, property, scope, client_id,
       value_type, value, description, created_at, updated_at
FROM app_platform_configs
WHERE id = $1
`

// Queries for app_platform_configs + app_platform_config_access. Two
// entity types, one repo (mirroring the Rust shape).
func (q *Queries) PlatformConfigFindByID(ctx context.Context, id string) (AppPlatformConfig, error) {
	row := q.db.QueryRow(ctx, platformConfigFindByID, id)
	var i AppPlatformConfig
	err := row.Scan(
		&i.ID,
		&i.ApplicationCode,
		&i.Section,
		&i.Property,
		&i.Scope,
		&i.ClientID,
		&i.ValueType,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const platformConfigUpsert = `-- name: PlatformConfigUpsert :exec
INSERT INTO app_platform_configs
    (id, application_code, section, property, scope, client_id,
     value_type, value, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    value_type = EXCLUDED.value_type,
    value = EXCLUDED.value,
    description = EXCLUDED.description,
    updated_at = EXCLUDED.updated_at
`

type PlatformConfigUpsertParams struct {
	ID              string    `db:"id"`
	ApplicationCode string    `db:"application_code"`
	Section         string    `db:"section"`
	Property        string    `db:"property"`
	Scope           string    `db:"scope"`
	ClientID        *string   `db:"client_id"`
	ValueType       string    `db:"value_type"`
	Value           string    `db:"value"`
	Description     *string   `db:"description"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
}

func (q *Queries) PlatformConfigUpsert(ctx context.Context, arg PlatformConfigUpsertParams) error {
	_, err := q.db.Exec(ctx, platformConfigUpsert,
		arg.ID,
		arg.ApplicationCode,
		arg.Section,
		arg.Property,
		arg.Scope,
		arg.ClientID,
		arg.ValueType,
		arg.Value,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
