// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principal.sql

package dbq

import (
	"context"
	"time"
)

const principalApplicationAccessClear = `-- name: PrincipalApplicationAccessClear :exec

DELETE FROM iam_principal_application_access WHERE principal_id = $1
`

// iam_principal_application_access + iam_client_access_grants do NOT have
// FK ON DELETE CASCADE on principal_id (only iam_principal_roles does), so
// Delete has to clean them explicitly. Mirrors Rust's delete() + Persist::delete.
func (q *Queries) PrincipalApplicationAccessClear(ctx context.Context, principalID string) error {
	_, err := q.db.Exec(ctx, principalApplicationAccessClear, principalID)
	return err
}

const principalClientAccessGrantsClear = `-- name: PrincipalClientAccessGrantsClear :exec
DELETE FROM iam_client_access_grants WHERE principal_id = $1
`

func (q *Queries) PrincipalClientAccessGrantsClear(ctx context.Context, principalID string) error {
	_, err := q.db.Exec(ctx, principalClientAccessGrantsClear, principalID)
	return err
}

const principalDelete = `-- name: PrincipalDelete :exec
DELETE FROM iam_principals WHERE id = $1
`

func (q *Queries) PrincipalDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, principalDelete, id)
	return err
}

const principalFindAll = `-- name: PrincipalFindAll :many
SELECT id, type, scope, client_id, application_id, name, active,
       email, email_domain, idp_type, external_idp_id, password_hash,
       last_login_at, service_account_id, created_at, updated_at, all_applications
FROM iam_principals
ORDER BY created_at DESC
`

func (q *Queries) PrincipalFindAll(ctx context.Context) ([]IamPrincipal, error) {
	rows, err := q.db.Query(ctx, principalFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamPrincipal{}
	for rows.Next() {
		var i IamPrincipal
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Scope,
			&i.ClientID,
			&i.ApplicationID,
			&i.Name,
			&i.Active,
			&i.Email,
			&i.EmailDomain,
			&i.IdpType,
			&i.ExternalIdpID,
			&i.PasswordHash,
			&i.LastLoginAt,
			&i.ServiceAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AllApplications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const principalFindByEmail = `-- name: PrincipalFindByEmail :one
SELECT id, type, scope, client_id, application_id, name, active,
       email, email_domain, idp_type, external_idp_id, password_hash,
       last_login_at, service_account_id, created_at, updated_at, all_applications
FROM iam_principals
WHERE type = 'USER' AND LOWER(email) = $1
`

// Case-insensitive match: emails are stored lower-cased (see repository.Persist),
// but callers pass values from sources whose casing we don't control (OIDC
// tokens, the login form). LOWER(email) also finds any legacy mixed-case row so
// the login self-heal can normalise it. The repo lower-cases $1 before binding.
func (q *Queries) PrincipalFindByEmail(ctx context.Context, email *string) (IamPrincipal, error) {
	row := q.db.QueryRow(ctx, principalFindByEmail, email)
	var i IamPrincipal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Scope,
		&i.ClientID,
		&i.ApplicationID,
		&i.Name,
		&i.Active,
		&i.Email,
		&i.EmailDomain,
		&i.IdpType,
		&i.ExternalIdpID,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.ServiceAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllApplications,
	)
	return i, err
}

const principalFindByID = `-- name: PrincipalFindByID :one

SELECT id, type, scope, client_id, application_id, name, active,
       email, email_domain, idp_type, external_idp_id, password_hash,
       last_login_at, service_account_id, created_at, updated_at, all_applications
FROM iam_principals
WHERE id = $1
`

// Queries for iam_principals + junction tables.
//
// The schema stores user-identity fields as flat columns (email, email_domain,
// idp_type, external_idp_id, password_hash, last_login_at) rather than the
// JSONB blobs the Go entity carries. Mapping happens in repository.go.
func (q *Queries) PrincipalFindByID(ctx context.Context, id string) (IamPrincipal, error) {
	row := q.db.QueryRow(ctx, principalFindByID, id)
	var i IamPrincipal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Scope,
		&i.ClientID,
		&i.ApplicationID,
		&i.Name,
		&i.Active,
		&i.Email,
		&i.EmailDomain,
		&i.IdpType,
		&i.ExternalIdpID,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.ServiceAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllApplications,
	)
	return i, err
}

const principalFindByServiceAccount = `-- name: PrincipalFindByServiceAccount :one
SELECT id, type, scope, client_id, application_id, name, active,
       email, email_domain, idp_type, external_idp_id, password_hash,
       last_login_at, service_account_id, created_at, updated_at, all_applications
FROM iam_principals
WHERE type = 'SERVICE' AND service_account_id = $1
`

func (q *Queries) PrincipalFindByServiceAccount(ctx context.Context, serviceAccountID *string) (IamPrincipal, error) {
	row := q.db.QueryRow(ctx, principalFindByServiceAccount, serviceAccountID)
	var i IamPrincipal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Scope,
		&i.ClientID,
		&i.ApplicationID,
		&i.Name,
		&i.Active,
		&i.Email,
		&i.EmailDomain,
		&i.IdpType,
		&i.ExternalIdpID,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.ServiceAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllApplications,
	)
	return i, err
}

const principalUpsert = `-- name: PrincipalUpsert :exec
INSERT INTO iam_principals
    (id, type, scope, client_id, application_id, name, active,
     email, email_domain, idp_type, external_idp_id, password_hash,
     last_login_at, service_account_id, all_applications, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    scope = EXCLUDED.scope,
    client_id = EXCLUDED.client_id,
    application_id = EXCLUDED.application_id,
    name = EXCLUDED.name,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    email_domain = EXCLUDED.email_domain,
    idp_type = EXCLUDED.idp_type,
    external_idp_id = EXCLUDED.external_idp_id,
    password_hash = EXCLUDED.password_hash,
    last_login_at = EXCLUDED.last_login_at,
    service_account_id = EXCLUDED.service_account_id,
    all_applications = EXCLUDED.all_applications,
    updated_at = EXCLUDED.updated_at
`

type PrincipalUpsertParams struct {
	ID               string     `db:"id"`
	Type             string     `db:"type"`
	Scope            *string    `db:"scope"`
	ClientID         *string    `db:"client_id"`
	ApplicationID    *string    `db:"application_id"`
	Name             string     `db:"name"`
	Active           bool       `db:"active"`
	Email            *string    `db:"email"`
	EmailDomain      *string    `db:"email_domain"`
	IdpType          *string    `db:"idp_type"`
	ExternalIdpID    *string    `db:"external_idp_id"`
	PasswordHash     *string    `db:"password_hash"`
	LastLoginAt      *time.Time `db:"last_login_at"`
	ServiceAccountID *string    `db:"service_account_id"`
	AllApplications  bool       `db:"all_applications"`
	CreatedAt        time.Time  `db:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at"`
}

func (q *Queries) PrincipalUpsert(ctx context.Context, arg PrincipalUpsertParams) error {
	_, err := q.db.Exec(ctx, principalUpsert,
		arg.ID,
		arg.Type,
		arg.Scope,
		arg.ClientID,
		arg.ApplicationID,
		arg.Name,
		arg.Active,
		arg.Email,
		arg.EmailDomain,
		arg.IdpType,
		arg.ExternalIdpID,
		arg.PasswordHash,
		arg.LastLoginAt,
		arg.ServiceAccountID,
		arg.AllApplications,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
