// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: process.sql

package dbq

import (
	"context"
	"time"
)

const processDelete = `-- name: ProcessDelete :exec
DELETE FROM msg_processes WHERE id = $1
`

func (q *Queries) ProcessDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, processDelete, id)
	return err
}

const processFindByCode = `-- name: ProcessFindByCode :one
SELECT id, code, name, description, status, source, application, subdomain,
       process_name, body, diagram_type, tags, created_at, updated_at
FROM msg_processes
WHERE code = $1
`

func (q *Queries) ProcessFindByCode(ctx context.Context, code string) (MsgProcess, error) {
	row := q.db.QueryRow(ctx, processFindByCode, code)
	var i MsgProcess
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Source,
		&i.Application,
		&i.Subdomain,
		&i.ProcessName,
		&i.Body,
		&i.DiagramType,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const processFindByID = `-- name: ProcessFindByID :one

SELECT id, code, name, description, status, source, application, subdomain,
       process_name, body, diagram_type, tags, created_at, updated_at
FROM msg_processes
WHERE id = $1
`

// Queries for msg_processes. The schema has no created_by column —
// matches the Rust source which hard-codes CreatedBy: None on read.
func (q *Queries) ProcessFindByID(ctx context.Context, id string) (MsgProcess, error) {
	row := q.db.QueryRow(ctx, processFindByID, id)
	var i MsgProcess
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Source,
		&i.Application,
		&i.Subdomain,
		&i.ProcessName,
		&i.Body,
		&i.DiagramType,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const processUpsert = `-- name: ProcessUpsert :exec
INSERT INTO msg_processes
    (id, code, name, description, status, source, application, subdomain,
     process_name, body, diagram_type, tags, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    body = EXCLUDED.body,
    diagram_type = EXCLUDED.diagram_type,
    tags = EXCLUDED.tags,
    updated_at = EXCLUDED.updated_at
`

type ProcessUpsertParams struct {
	ID          string    `db:"id"`
	Code        string    `db:"code"`
	Name        string    `db:"name"`
	Description *string   `db:"description"`
	Status      string    `db:"status"`
	Source      string    `db:"source"`
	Application string    `db:"application"`
	Subdomain   string    `db:"subdomain"`
	ProcessName string    `db:"process_name"`
	Body        string    `db:"body"`
	DiagramType string    `db:"diagram_type"`
	Tags        []string  `db:"tags"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

func (q *Queries) ProcessUpsert(ctx context.Context, arg ProcessUpsertParams) error {
	_, err := q.db.Exec(ctx, processUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Source,
		arg.Application,
		arg.Subdomain,
		arg.ProcessName,
		arg.Body,
		arg.DiagramType,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
