// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package dbq

import (
	"context"
	"time"
)

const roleDelete = `-- name: RoleDelete :exec
DELETE FROM iam_roles WHERE id = $1
`

func (q *Queries) RoleDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, roleDelete, id)
	return err
}

const roleFindAll = `-- name: RoleFindAll :many
SELECT id, application_id, application_code, name, display_name, description,
       source, client_managed, created_at, updated_at
FROM iam_roles
ORDER BY name
`

func (q *Queries) RoleFindAll(ctx context.Context) ([]IamRole, error) {
	rows, err := q.db.Query(ctx, roleFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamRole{}
	for rows.Next() {
		var i IamRole
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ApplicationCode,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Source,
			&i.ClientManaged,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleFindByID = `-- name: RoleFindByID :one

SELECT id, application_id, application_code, name, display_name, description,
       source, client_managed, created_at, updated_at
FROM iam_roles
WHERE id = $1
`

// Queries for iam_roles + iam_role_permissions. Permissions are
// many-to-many; Persist replaces them wholesale.
func (q *Queries) RoleFindByID(ctx context.Context, id string) (IamRole, error) {
	row := q.db.QueryRow(ctx, roleFindByID, id)
	var i IamRole
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ApplicationCode,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Source,
		&i.ClientManaged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const roleFindByName = `-- name: RoleFindByName :one
SELECT id, application_id, application_code, name, display_name, description,
       source, client_managed, created_at, updated_at
FROM iam_roles
WHERE name = $1
`

func (q *Queries) RoleFindByName(ctx context.Context, name string) (IamRole, error) {
	row := q.db.QueryRow(ctx, roleFindByName, name)
	var i IamRole
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ApplicationCode,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Source,
		&i.ClientManaged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rolePermissionInsert = `-- name: RolePermissionInsert :exec
INSERT INTO iam_role_permissions (role_id, permission)
VALUES ($1, $2)
`

type RolePermissionInsertParams struct {
	RoleID     string
	Permission string
}

func (q *Queries) RolePermissionInsert(ctx context.Context, arg RolePermissionInsertParams) error {
	_, err := q.db.Exec(ctx, rolePermissionInsert, arg.RoleID, arg.Permission)
	return err
}

const rolePermissionsClear = `-- name: RolePermissionsClear :exec
DELETE FROM iam_role_permissions WHERE role_id = $1
`

func (q *Queries) RolePermissionsClear(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, rolePermissionsClear, roleID)
	return err
}

const rolePermissionsForRoles = `-- name: RolePermissionsForRoles :many
SELECT role_id, permission
FROM iam_role_permissions
WHERE role_id = ANY($1::text[])
`

func (q *Queries) RolePermissionsForRoles(ctx context.Context, roleIds []string) ([]IamRolePermission, error) {
	rows, err := q.db.Query(ctx, rolePermissionsForRoles, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamRolePermission{}
	for rows.Next() {
		var i IamRolePermission
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleUpsert = `-- name: RoleUpsert :exec
INSERT INTO iam_roles
    (id, application_id, name, display_name, description, application_code,
     source, client_managed, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    application_id = EXCLUDED.application_id,
    name = EXCLUDED.name,
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    application_code = EXCLUDED.application_code,
    source = EXCLUDED.source,
    client_managed = EXCLUDED.client_managed,
    updated_at = EXCLUDED.updated_at
`

type RoleUpsertParams struct {
	ID              string
	ApplicationID   *string
	Name            string
	DisplayName     string
	Description     *string
	ApplicationCode *string
	Source          string
	ClientManaged   bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) RoleUpsert(ctx context.Context, arg RoleUpsertParams) error {
	_, err := q.db.Exec(ctx, roleUpsert,
		arg.ID,
		arg.ApplicationID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.ApplicationCode,
		arg.Source,
		arg.ClientManaged,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
