// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduledjob.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const scheduledJobDelete = `-- name: ScheduledJobDelete :exec
DELETE FROM msg_scheduled_jobs WHERE id = $1
`

func (q *Queries) ScheduledJobDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, scheduledJobDelete, id)
	return err
}

const scheduledJobFindActive = `-- name: ScheduledJobFindActive :many
SELECT id, client_id, code, name, description, status, crons, timezone,
       payload, concurrent, tracks_completion, timeout_seconds,
       delivery_max_attempts, target_url, last_fired_at,
       created_at, updated_at, created_by, updated_by, version
FROM msg_scheduled_jobs
WHERE status = 'ACTIVE'
`

func (q *Queries) ScheduledJobFindActive(ctx context.Context) ([]MsgScheduledJob, error) {
	rows, err := q.db.Query(ctx, scheduledJobFindActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgScheduledJob{}
	for rows.Next() {
		var i MsgScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Crons,
			&i.Timezone,
			&i.Payload,
			&i.Concurrent,
			&i.TracksCompletion,
			&i.TimeoutSeconds,
			&i.DeliveryMaxAttempts,
			&i.TargetUrl,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduledJobFindAll = `-- name: ScheduledJobFindAll :many
SELECT id, client_id, code, name, description, status, crons, timezone,
       payload, concurrent, tracks_completion, timeout_seconds,
       delivery_max_attempts, target_url, last_fired_at,
       created_at, updated_at, created_by, updated_by, version
FROM msg_scheduled_jobs
ORDER BY code
`

func (q *Queries) ScheduledJobFindAll(ctx context.Context) ([]MsgScheduledJob, error) {
	rows, err := q.db.Query(ctx, scheduledJobFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgScheduledJob{}
	for rows.Next() {
		var i MsgScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Crons,
			&i.Timezone,
			&i.Payload,
			&i.Concurrent,
			&i.TracksCompletion,
			&i.TimeoutSeconds,
			&i.DeliveryMaxAttempts,
			&i.TargetUrl,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduledJobFindByCodeClient = `-- name: ScheduledJobFindByCodeClient :one
SELECT id, client_id, code, name, description, status, crons, timezone,
       payload, concurrent, tracks_completion, timeout_seconds,
       delivery_max_attempts, target_url, last_fired_at,
       created_at, updated_at, created_by, updated_by, version
FROM msg_scheduled_jobs
WHERE code = $1 AND client_id = $2
`

type ScheduledJobFindByCodeClientParams struct {
	Code     string  `db:"code"`
	ClientID *string `db:"client_id"`
}

func (q *Queries) ScheduledJobFindByCodeClient(ctx context.Context, arg ScheduledJobFindByCodeClientParams) (MsgScheduledJob, error) {
	row := q.db.QueryRow(ctx, scheduledJobFindByCodeClient, arg.Code, arg.ClientID)
	var i MsgScheduledJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Crons,
		&i.Timezone,
		&i.Payload,
		&i.Concurrent,
		&i.TracksCompletion,
		&i.TimeoutSeconds,
		&i.DeliveryMaxAttempts,
		&i.TargetUrl,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const scheduledJobFindByCodePlatform = `-- name: ScheduledJobFindByCodePlatform :one
SELECT id, client_id, code, name, description, status, crons, timezone,
       payload, concurrent, tracks_completion, timeout_seconds,
       delivery_max_attempts, target_url, last_fired_at,
       created_at, updated_at, created_by, updated_by, version
FROM msg_scheduled_jobs
WHERE code = $1 AND client_id IS NULL
`

func (q *Queries) ScheduledJobFindByCodePlatform(ctx context.Context, code string) (MsgScheduledJob, error) {
	row := q.db.QueryRow(ctx, scheduledJobFindByCodePlatform, code)
	var i MsgScheduledJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Crons,
		&i.Timezone,
		&i.Payload,
		&i.Concurrent,
		&i.TracksCompletion,
		&i.TimeoutSeconds,
		&i.DeliveryMaxAttempts,
		&i.TargetUrl,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const scheduledJobFindByID = `-- name: ScheduledJobFindByID :one

SELECT id, client_id, code, name, description, status, crons, timezone,
       payload, concurrent, tracks_completion, timeout_seconds,
       delivery_max_attempts, target_url, last_fired_at,
       created_at, updated_at, created_by, updated_by, version
FROM msg_scheduled_jobs
WHERE id = $1
`

// Queries for msg_scheduled_jobs. Schema (migration 021) matches the
// Go entity 1:1 — straightforward port.
func (q *Queries) ScheduledJobFindByID(ctx context.Context, id string) (MsgScheduledJob, error) {
	row := q.db.QueryRow(ctx, scheduledJobFindByID, id)
	var i MsgScheduledJob
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Crons,
		&i.Timezone,
		&i.Payload,
		&i.Concurrent,
		&i.TracksCompletion,
		&i.TimeoutSeconds,
		&i.DeliveryMaxAttempts,
		&i.TargetUrl,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const scheduledJobUpsert = `-- name: ScheduledJobUpsert :exec
INSERT INTO msg_scheduled_jobs
    (id, client_id, code, name, description, status, crons, timezone,
     payload, concurrent, tracks_completion, timeout_seconds,
     delivery_max_attempts, target_url, last_fired_at,
     created_at, updated_at, created_by, updated_by, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18, $19, $20)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    crons = EXCLUDED.crons,
    timezone = EXCLUDED.timezone,
    payload = EXCLUDED.payload,
    concurrent = EXCLUDED.concurrent,
    tracks_completion = EXCLUDED.tracks_completion,
    timeout_seconds = EXCLUDED.timeout_seconds,
    delivery_max_attempts = EXCLUDED.delivery_max_attempts,
    target_url = EXCLUDED.target_url,
    last_fired_at = EXCLUDED.last_fired_at,
    updated_at = EXCLUDED.updated_at,
    updated_by = EXCLUDED.updated_by,
    version = EXCLUDED.version
`

type ScheduledJobUpsertParams struct {
	ID                  string          `db:"id"`
	ClientID            *string         `db:"client_id"`
	Code                string          `db:"code"`
	Name                string          `db:"name"`
	Description         *string         `db:"description"`
	Status              string          `db:"status"`
	Crons               []string        `db:"crons"`
	Timezone            string          `db:"timezone"`
	Payload             json.RawMessage `db:"payload"`
	Concurrent          bool            `db:"concurrent"`
	TracksCompletion    bool            `db:"tracks_completion"`
	TimeoutSeconds      *int32          `db:"timeout_seconds"`
	DeliveryMaxAttempts int32           `db:"delivery_max_attempts"`
	TargetUrl           *string         `db:"target_url"`
	LastFiredAt         *time.Time      `db:"last_fired_at"`
	CreatedAt           time.Time       `db:"created_at"`
	UpdatedAt           time.Time       `db:"updated_at"`
	CreatedBy           *string         `db:"created_by"`
	UpdatedBy           *string         `db:"updated_by"`
	Version             int32           `db:"version"`
}

func (q *Queries) ScheduledJobUpsert(ctx context.Context, arg ScheduledJobUpsertParams) error {
	_, err := q.db.Exec(ctx, scheduledJobUpsert,
		arg.ID,
		arg.ClientID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Crons,
		arg.Timezone,
		arg.Payload,
		arg.Concurrent,
		arg.TracksCompletion,
		arg.TimeoutSeconds,
		arg.DeliveryMaxAttempts,
		arg.TargetUrl,
		arg.LastFiredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Version,
	)
	return err
}
