// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serviceaccount.sql

package dbq

import (
	"context"
	"time"

	"github.com/flowcatalyst/flowcatalyst-go/internal/ids"
)

const serviceAccountDelete = `-- name: ServiceAccountDelete :exec
DELETE FROM iam_service_accounts WHERE id = $1
`

func (q *Queries) ServiceAccountDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, serviceAccountDelete, id)
	return err
}

const serviceAccountDeleteOAuthClients = `-- name: ServiceAccountDeleteOAuthClients :exec
DELETE FROM oauth_clients
 WHERE service_account_principal_id IN
       (SELECT id FROM iam_principals WHERE service_account_id = $1)
`

// The OAuth clients wired to the account's SERVICE principal. Migration 027's
// FK would cascade them with the principal; deleted explicitly anyway so the
// order is visible and an install without the FK is covered.
func (q *Queries) ServiceAccountDeleteOAuthClients(ctx context.Context, serviceAccountID *string) error {
	_, err := q.db.Exec(ctx, serviceAccountDeleteOAuthClients, serviceAccountID)
	return err
}

const serviceAccountDeletePrincipalApplicationAccess = `-- name: ServiceAccountDeletePrincipalApplicationAccess :exec
DELETE FROM iam_principal_application_access
 WHERE principal_id IN (SELECT id FROM iam_principals WHERE service_account_id = $1)
`

// iam_principal_application_access has no FK cascade on principal_id.
func (q *Queries) ServiceAccountDeletePrincipalApplicationAccess(ctx context.Context, serviceAccountID *string) error {
	_, err := q.db.Exec(ctx, serviceAccountDeletePrincipalApplicationAccess, serviceAccountID)
	return err
}

const serviceAccountDeletePrincipalClientGrants = `-- name: ServiceAccountDeletePrincipalClientGrants :exec
DELETE FROM iam_client_access_grants
 WHERE principal_id IN (SELECT id FROM iam_principals WHERE service_account_id = $1)
`

// iam_client_access_grants has no FK cascade on principal_id.
func (q *Queries) ServiceAccountDeletePrincipalClientGrants(ctx context.Context, serviceAccountID *string) error {
	_, err := q.db.Exec(ctx, serviceAccountDeletePrincipalClientGrants, serviceAccountID)
	return err
}

const serviceAccountDeletePrincipals = `-- name: ServiceAccountDeletePrincipals :exec
DELETE FROM iam_principals WHERE service_account_id = $1
`

// The account's SERVICE principal. Its role rows cascade
// (iam_principal_roles), and an application pointing at it is set NULL
// (migration 028).
func (q *Queries) ServiceAccountDeletePrincipals(ctx context.Context, serviceAccountID *string) error {
	_, err := q.db.Exec(ctx, serviceAccountDeletePrincipals, serviceAccountID)
	return err
}

const serviceAccountFindAll = `-- name: ServiceAccountFindAll :many
SELECT id, code, name, description, application_id, active,
       wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
       wh_signing_algorithm, wh_credentials_created_at,
       wh_credentials_regenerated_at, last_used_at, created_at, updated_at,
       scope, client_ids
FROM iam_service_accounts
ORDER BY code
`

func (q *Queries) ServiceAccountFindAll(ctx context.Context) ([]IamServiceAccount, error) {
	rows, err := q.db.Query(ctx, serviceAccountFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamServiceAccount{}
	for rows.Next() {
		var i IamServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ApplicationID,
			&i.Active,
			&i.WhAuthType,
			&i.WhAuthTokenRef,
			&i.WhSigningSecretRef,
			&i.WhSigningAlgorithm,
			&i.WhCredentialsCreatedAt,
			&i.WhCredentialsRegeneratedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.ClientIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceAccountFindByCode = `-- name: ServiceAccountFindByCode :one
SELECT id, code, name, description, application_id, active,
       wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
       wh_signing_algorithm, wh_credentials_created_at,
       wh_credentials_regenerated_at, last_used_at, created_at, updated_at,
       scope, client_ids
FROM iam_service_accounts
WHERE code = $1
`

func (q *Queries) ServiceAccountFindByCode(ctx context.Context, code string) (IamServiceAccount, error) {
	row := q.db.QueryRow(ctx, serviceAccountFindByCode, code)
	var i IamServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ApplicationID,
		&i.Active,
		&i.WhAuthType,
		&i.WhAuthTokenRef,
		&i.WhSigningSecretRef,
		&i.WhSigningAlgorithm,
		&i.WhCredentialsCreatedAt,
		&i.WhCredentialsRegeneratedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.ClientIds,
	)
	return i, err
}

const serviceAccountFindByID = `-- name: ServiceAccountFindByID :one

SELECT id, code, name, description, application_id, active,
       wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
       wh_signing_algorithm, wh_credentials_created_at,
       wh_credentials_regenerated_at, last_used_at, created_at, updated_at,
       scope, client_ids
FROM iam_service_accounts
WHERE id = $1
`

// Queries for iam_service_accounts. Webhook credentials are stored as
// separate columns (wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
// wh_signing_algorithm) matching the wire contract. The repository maps the flat
// columns into a single WebhookCredentials struct in the aggregate.
func (q *Queries) ServiceAccountFindByID(ctx context.Context, id string) (IamServiceAccount, error) {
	row := q.db.QueryRow(ctx, serviceAccountFindByID, id)
	var i IamServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ApplicationID,
		&i.Active,
		&i.WhAuthType,
		&i.WhAuthTokenRef,
		&i.WhSigningSecretRef,
		&i.WhSigningAlgorithm,
		&i.WhCredentialsCreatedAt,
		&i.WhCredentialsRegeneratedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.ClientIds,
	)
	return i, err
}

const serviceAccountFindFirstByApplicationID = `-- name: ServiceAccountFindFirstByApplicationID :one
SELECT sa.id, sa.code, sa.name, sa.description, sa.application_id, sa.active,
       sa.wh_auth_type, sa.wh_auth_token_ref, sa.wh_signing_secret_ref,
       sa.wh_signing_algorithm, sa.wh_credentials_created_at,
       sa.wh_credentials_regenerated_at, sa.last_used_at, sa.created_at, sa.updated_at,
       sa.scope, sa.client_ids
FROM iam_service_accounts sa
WHERE sa.application_id = $1 AND sa.active = TRUE
ORDER BY
    (CASE WHEN EXISTS (
        SELECT 1
        FROM app_applications a
        JOIN iam_principals p ON p.id = a.service_account_id
        WHERE a.id = sa.application_id AND p.service_account_id = sa.id
    ) THEN 0 ELSE 1 END),
    sa.created_at ASC
LIMIT 1
`

// The SA whose credentials sign the application's outbound deliveries.
// Deterministic preference: the application's own provisioned service
// account (app_applications.service_account_id → SERVICE principal →
// iam_service_accounts) wins over any other SA that merely carries the
// application_id; among the rest, oldest active first. Without this an app
// with several linked SAs could sign with one SA while the operator rotates
// credentials on another.
func (q *Queries) ServiceAccountFindFirstByApplicationID(ctx context.Context, applicationID *ids.ApplicationID) (IamServiceAccount, error) {
	row := q.db.QueryRow(ctx, serviceAccountFindFirstByApplicationID, applicationID)
	var i IamServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ApplicationID,
		&i.Active,
		&i.WhAuthType,
		&i.WhAuthTokenRef,
		&i.WhSigningSecretRef,
		&i.WhSigningAlgorithm,
		&i.WhCredentialsCreatedAt,
		&i.WhCredentialsRegeneratedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.ClientIds,
	)
	return i, err
}

const serviceAccountRenamePrincipal = `-- name: ServiceAccountRenamePrincipal :exec
UPDATE iam_principals
   SET name = $2
 WHERE service_account_id = $1
   AND name IS DISTINCT FROM $2
`

type ServiceAccountRenamePrincipalParams struct {
	ServiceAccountID *string `db:"service_account_id"`
	Name             string  `db:"name"`
}

// Keeps the SERVICE principal's name in step with its account's, so a token
// minted after a rename carries the new name. updated_at is left alone on
// purpose: it is the principal's token version, and renaming an account must
// not revoke its live tokens.
func (q *Queries) ServiceAccountRenamePrincipal(ctx context.Context, arg ServiceAccountRenamePrincipalParams) error {
	_, err := q.db.Exec(ctx, serviceAccountRenamePrincipal, arg.ServiceAccountID, arg.Name)
	return err
}

const serviceAccountUpsert = `-- name: ServiceAccountUpsert :exec
INSERT INTO iam_service_accounts
    (id, code, name, description, application_id, scope, client_ids, active,
     wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
     wh_signing_algorithm, wh_credentials_created_at,
     wh_credentials_regenerated_at, last_used_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    application_id = EXCLUDED.application_id,
    scope = EXCLUDED.scope,
    client_ids = EXCLUDED.client_ids,
    active = EXCLUDED.active,
    wh_auth_type = EXCLUDED.wh_auth_type,
    wh_auth_token_ref = EXCLUDED.wh_auth_token_ref,
    wh_signing_secret_ref = EXCLUDED.wh_signing_secret_ref,
    wh_signing_algorithm = EXCLUDED.wh_signing_algorithm,
    wh_credentials_created_at = EXCLUDED.wh_credentials_created_at,
    wh_credentials_regenerated_at = EXCLUDED.wh_credentials_regenerated_at,
    last_used_at = EXCLUDED.last_used_at,
    updated_at = EXCLUDED.updated_at
`

type ServiceAccountUpsertParams struct {
	ID                         string             `db:"id"`
	Code                       string             `db:"code"`
	Name                       string             `db:"name"`
	Description                *string            `db:"description"`
	ApplicationID              *ids.ApplicationID `db:"application_id"`
	Scope                      *string            `db:"scope"`
	ClientIds                  []string           `db:"client_ids"`
	Active                     bool               `db:"active"`
	WhAuthType                 *string            `db:"wh_auth_type"`
	WhAuthTokenRef             *string            `db:"wh_auth_token_ref"`
	WhSigningSecretRef         *string            `db:"wh_signing_secret_ref"`
	WhSigningAlgorithm         *string            `db:"wh_signing_algorithm"`
	WhCredentialsCreatedAt     *time.Time         `db:"wh_credentials_created_at"`
	WhCredentialsRegeneratedAt *time.Time         `db:"wh_credentials_regenerated_at"`
	LastUsedAt                 *time.Time         `db:"last_used_at"`
	CreatedAt                  time.Time          `db:"created_at"`
	UpdatedAt                  time.Time          `db:"updated_at"`
}

func (q *Queries) ServiceAccountUpsert(ctx context.Context, arg ServiceAccountUpsertParams) error {
	_, err := q.db.Exec(ctx, serviceAccountUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ApplicationID,
		arg.Scope,
		arg.ClientIds,
		arg.Active,
		arg.WhAuthType,
		arg.WhAuthTokenRef,
		arg.WhSigningSecretRef,
		arg.WhSigningAlgorithm,
		arg.WhCredentialsCreatedAt,
		arg.WhCredentialsRegeneratedAt,
		arg.LastUsedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
