// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_ceremony.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const webauthnCeremonyConsume = `-- name: WebauthnCeremonyConsume :one
DELETE FROM oauth_oidc_payloads
WHERE id = $1 AND (expires_at IS NULL OR expires_at > NOW())
RETURNING payload
`

func (q *Queries) WebauthnCeremonyConsume(ctx context.Context, id string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, webauthnCeremonyConsume, id)
	var payload json.RawMessage
	err := row.Scan(&payload)
	return payload, err
}

const webauthnCeremonyPurgeExpired = `-- name: WebauthnCeremonyPurgeExpired :execrows
DELETE FROM oauth_oidc_payloads
WHERE type IN ($1, $2)
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
`

type WebauthnCeremonyPurgeExpiredParams struct {
	Type   string
	Type_2 string
}

func (q *Queries) WebauthnCeremonyPurgeExpired(ctx context.Context, arg WebauthnCeremonyPurgeExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, webauthnCeremonyPurgeExpired, arg.Type, arg.Type_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const webauthnCeremonyUpsert = `-- name: WebauthnCeremonyUpsert :exec

INSERT INTO oauth_oidc_payloads (id, type, payload, expires_at, created_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (id) DO UPDATE SET
    payload = EXCLUDED.payload,
    expires_at = EXCLUDED.expires_at
`

type WebauthnCeremonyUpsertParams struct {
	ID        string
	Type      string
	Payload   json.RawMessage
	ExpiresAt *time.Time
}

// Queries for WebAuthn ceremony state in oauth_oidc_payloads.
// The id column carries a type prefix ("WebauthnRegistration:{stateID}")
// to keep ids unique across the shared store; the type column carries
// the same discriminant. Mirrors the Rust impl.
func (q *Queries) WebauthnCeremonyUpsert(ctx context.Context, arg WebauthnCeremonyUpsertParams) error {
	_, err := q.db.Exec(ctx, webauthnCeremonyUpsert,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.ExpiresAt,
	)
	return err
}
