// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const webauthnCredentialDelete = `-- name: WebauthnCredentialDelete :exec
DELETE FROM webauthn_credentials WHERE id = $1
`

func (q *Queries) WebauthnCredentialDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, webauthnCredentialDelete, id)
	return err
}

const webauthnCredentialFindByCredentialID = `-- name: WebauthnCredentialFindByCredentialID :one
SELECT id, principal_id, credential_id, passkey_data, name, created_at, last_used_at
FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) WebauthnCredentialFindByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, webauthnCredentialFindByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.CredentialID,
		&i.PasskeyData,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const webauthnCredentialFindByID = `-- name: WebauthnCredentialFindByID :one

SELECT id, principal_id, credential_id, passkey_data, name, created_at, last_used_at
FROM webauthn_credentials
WHERE id = $1
`

// Queries for webauthn_credentials.
// Column is passkey_data (JSONB), not "credential" — the entity field
// name and the column name differ.
func (q *Queries) WebauthnCredentialFindByID(ctx context.Context, id string) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, webauthnCredentialFindByID, id)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.CredentialID,
		&i.PasskeyData,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const webauthnCredentialFindByPrincipal = `-- name: WebauthnCredentialFindByPrincipal :many
SELECT id, principal_id, credential_id, passkey_data, name, created_at, last_used_at
FROM webauthn_credentials
WHERE principal_id = $1
ORDER BY created_at
`

func (q *Queries) WebauthnCredentialFindByPrincipal(ctx context.Context, principalID string) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, webauthnCredentialFindByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.CredentialID,
			&i.PasskeyData,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webauthnCredentialUpsert = `-- name: WebauthnCredentialUpsert :exec
INSERT INTO webauthn_credentials
    (id, principal_id, credential_id, passkey_data, name, created_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    passkey_data = EXCLUDED.passkey_data,
    name = EXCLUDED.name,
    last_used_at = EXCLUDED.last_used_at
`

type WebauthnCredentialUpsertParams struct {
	ID           string          `db:"id"`
	PrincipalID  string          `db:"principal_id"`
	CredentialID []byte          `db:"credential_id"`
	PasskeyData  json.RawMessage `db:"passkey_data"`
	Name         *string         `db:"name"`
	CreatedAt    time.Time       `db:"created_at"`
	LastUsedAt   *time.Time      `db:"last_used_at"`
}

func (q *Queries) WebauthnCredentialUpsert(ctx context.Context, arg WebauthnCredentialUpsertParams) error {
	_, err := q.db.Exec(ctx, webauthnCredentialUpsert,
		arg.ID,
		arg.PrincipalID,
		arg.CredentialID,
		arg.PasskeyData,
		arg.Name,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}
